### PR TITLE
fix builtin.autocommands throwing error

### PR DESCRIPTION
**Pull request by Vedant36**
im `pcall` ing it as per the suggestion of @Conni2461
i also removed the vim.schedule as the other previewers didn't need it either
Fixes: #1754

### CODE REVIEW

**Comment by Vedant36** [comment]
sure i'll add the commit.
i am able to scroll the preview window without that line there, but you probably understand it better

**Comment by daangoossens22** [comment]
I didn't intend to sound nosy, I added the vim.schedule part in a previous pull request so I wanted to chime in.
It is not about being able to scroll the preview window manually, but that it does so automatically while fuzzy finding. Here to show it visually (without manually scrolling the preview window):
- pcall, no vim.schedule:
no_schedule
- pcall, with vim.schedule:
with_schedule

**Comment by Vedant36** [comment]
10/10 explanation. i understand the reason now

**Review by Conni2461 — APPROVED** [review]
yep i only wanted an additional `pcall` to suppress the error message :laughing: 

LGTM thanks :)

**Pull request merged**
