### PR TITLE
fix(command parser): discard invalid lua expressions

### PR DESCRIPTION
**Pull request by l-kershaw**
Fix issue from [this](https://github.com/nvim-telescope/telescope.nvim/pull/1075#issuecomment-901371701) comment.

@gizmo385 could you let me know if this fixes the issue on your end?

### CODE REVIEW

**Comment by fdschmidt93** [comment]
`:Telescope find_files find_command=rg,--ignore,--hidden,--files prompt_prefix=🔍 layout_config={'prompt_position':'top'}` or `:Telescope find_files find_command=rg,--ignore,--hidden,--files prompt_prefix=🔍 theme=get_ivy` work for me on this PR, validating this and the old one simultaneously :)

Not sure what other complicated things to test as all kinds of options seem to work accordingly (sorry, everthing otherwise is lua for me :). Do we have a meaningful table-of-tables opt that could be passed in layout config?

On an unrelated note, @l-kershaw you should join us on Gitter :)

**Comment by gizmo385** [comment]
@l-kershaw Checked out this branch this morning and things are working as expected! Thanks a bunch!

**Comment by Conni2461** [comment]
Thanks :)

**Comment by l-kershaw** [comment]
Ah, you beat me to it Conni 🤣

**Pull request merged**
