### PR TITLE
fix: the moon is not a planet

### PR DESCRIPTION
**Pull request by axieax**
# Description

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context

My inner astrologer just realised the moon is in `:Telescope planets`, but it ain't a planet :((

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

Very important bug fix (hopefully doesn't break things)!!

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

The moon is not one of the planets in this [credible source](https://en.wikipedia.org/wiki/File:Solar_System_true_color_(captions).jpg). Also Google says it ain't so it ain't. Please see the images below.

image

image

**Configuration**:
* Neovim version (nvim --version): nvim v0.7.2
* Operating system and version: arch btw

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

**Comment by razin99** [comment]
Great research on this issue, I agree this should be the case. Moon is a satellite.

**Comment by stevenp2** [comment]
perhaps it would have been better if you didn't completely remove the `moon` file, but treat it as an easter egg like `pluto`

**Comment by Conni2461** [comment]
I like @stevenp2 proposal more. Lets hide it behind a `show_moon` option

**Comment by Conni2461** [comment]
resolved by https://github.com/nvim-telescope/telescope.nvim/commit/b5833a682c511885887373aad76272ad70f7b3c2

Thanks for bringing up this bug :)

**Pull request closed without merging**
