### PR TITLE
Async lsp requests

### PR DESCRIPTION
**Pull request by p00f**
This PR tries to make the lsp requests async. I've implemented this for `references()` and `list_or_jump()` for now and would like feedback before doing the rest.
before:

https://user-images.githubusercontent.com/36493671/143772352-46c064bc-0c71-497a-8d30-e230e01940d9.mp4

after:

https://user-images.githubusercontent.com/36493671/143771369-e9bc7cb2-4419-4d31-a1db-496844ee83cb.mp4

### CODE REVIEW

**Comment by p00f** [comment]
I didn't see any situation where document symbols, workspace symbols or code actions would block neovim, should I still do it?

**Comment by p00f** [comment]
I did it anyway except for code actions because that function is 150 lines long and this might add more complexity. Let me know if I should do it

**Comment by p00f** [comment]
squashed

**Comment by tjdevries** [comment]
Seems good to me

**Comment by p00f** [comment]
Fixed formatting

**Review by Conni2461 — APPROVED** [review]
LGTM thanks :)

**Comment by Conni2461** [comment]
Yeah we ( I ) dont care that much about `code_actions` anymore. We might remove it in favor of `vim.lsp.buf.code_action` and advice to use `vim.select` with telescope if they need telescope for code actions

**Comment by clason** [comment]
OK, this broke my use of `'require"telescope.builtin".lsp_workspace_symbols()` (note the empty argument). How do I get this back? 😄

**Comment by Conni2461** [comment]
mb missed that while testing. patch is up in 2min

**Comment by clason** [comment]
(Sorry for not testing the PR before merge!)

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/1535

**Comment by p00f** [comment]
Sorry about that :cry:

**Pull request merged**
