### PR TITLE
Enhance Telescope command

### LINKED ISSUE #581: :Telescope should open builtin
Telescope subcommand is too much, if can use telescope to list all the subcomand, that's convenient.
Just like when I execute: 
`:Telescope`
it will list all the telescope subcommand with telescope itself, like: 

find_files
live_grep
buffers (cursor here)
help_tags
...

at this time, when I hit enter, it will execute `:Telescope buffers`

### PR DESCRIPTION
**Pull request by glepnir**
close #581 cc @Conni2461  @sunjon @singlexyz @elianiva

### CODE REVIEW

**Comment by elianiva** [comment]
LGTM

**Comment by glepnir** [comment]
has a bug .. fix now.

**Comment by glepnir** [comment]
fix. confirm works fine.

**Review by Conni2461 — APPROVED** [review]
LGTM

Thanks :)

**Pull request merged**
