### PR TITLE
fix(__internal) : fix slash problem in oldfiles

### LINKED ISSUE #1683: Duplicates path entries on Windows
### Description

There is duplication of entries when we are talking of paths, as seen in the screenshot below:
image

### Neovim version

```markdown
NVIM v0.7.0-dev+793-g991e872d8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. On windows, open a file a few times.
2. At some point it will duplicated in old_files, as there will be two path, one containing `\` the other having `\\`.

### Expected behavior

No duplication of paths, every folder/file have a single entry

### Actual behavior

Files and folders are sometimes duplicated due to having single or double forward slashes (as per screenshot in description)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by Jaehaks**
# Description

- Problems

Problem with slash and backslash being mixed up is chronic issue of neovim in Windows. it makes telescope prompt perceive same path differently when it execute to oldfiles picker.

some function like `nvim_buf_get_name()` or `vim.v.oldfiles` give paths which are mixed up with slash and backslash.

- What it did For windows, 

it always needs to change slash(/) to backslash(\) when function which deal with path because entry_maker works properly only the case that path string has \ not /.

- Effect

1) oldfiles picker doesn't show duplicated list
2) `defaults.path_display` configuration feature will works well at oldfiles pikcer

Fixes #1683
It is related with PR #3103 what i submitted but opened 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

- [ v ] Test A
1) open oldfiles picker 
2) path_display feature will works all entry of oldfiles. 
   (before the issue is fixed, the path which has slash and backslash being mixed up cannot be applied by path_display
   even though `vim.opt.shellslash` is `true`
image

I checked with formatter stylua also and add some simple comment about it

**Configuration**:
* Neovim version (nvim --version): v0.10.0
* Operating system and version: Windows 10

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

**Comment by jamestrew** [comment]
Sorry is this the same fix as https://github.com/nvim-telescope/telescope.nvim/pull/3103
Looks largely the same to me.

**Comment by Jaehaks** [comment]
@jamestrew 
Ok, I agree that the modification of `plenary.nvim` is fundamental solution. 
I hope your PR is accepted :)

**Comment by jamestrew** [comment]
Sorry I must've confused you with a comment I deleted about plenary.
I think this PR could still be helpful since this code path is dealing with file paths before plenary even comes into play.

I just wanted to confirm that this fixes the same issue as #3103 -- seems like a simpler fix so I'd probably prefer this PR over #3103 if that's alright.

I would probably just ask to remove all but the first `-- for slash problem in windows` comment.

**Comment by Jaehaks** [comment]
@jamestrew 

Ok, New commit is uploaded with erased comments except of first one. 
This PR is same with #3103, just I modified more precise because I don't know how to upload new commit before.

**Comment by jamestrew** [comment]
Thanks!

**Pull request merged**
