### PR TITLE
Error

### LINKED ISSUE #262: Telescope builtin: prompt in normal mode instead of insert mode
after running `:Telescope builtin` and selecting some picker, prompt is in normal mode instead of being in insert mode

### PR DESCRIPTION
**Pull request by tami5**
Damn by bad

### CODE REVIEW

**Comment by Conni2461** [comment]
Do a rebase on master. Force push and rename title :)

**Comment by tami5** [comment]
@Conni2461 :face_with_head_bandage: I can do that? wow I missed up real bad. already opened a new one. Thanks for the tab, lesson learned here :dagger:

**Comment by Conni2461** [comment]
No worries.

**Comment by tjdevries** [comment]
git is hard :) no worries.

**Pull request closed without merging**
