### PR TITLE
remove bat env theme variable

### LINKED ISSUE #488: Bat theme not picked up from environment
### Description
Bat theme not applied to the preview window. Gif at the end of description.

**Expected Behavior**
Expect telescope to read `$BAT_THEME` env variable

**Actual Behavior**
Looks like it uses the default

### Steps to reproduce
1. nvim -nu test.vim
2. :Telescope find_files
3. Find some file
4. Check preview
5. Exit neovim, open same file in bat from cli, see difference

### Environment
* nvim --version output: VIM v0.5.0-dev+1062-gcc1851c9f
* Operating system: Manjaro Linux 
* Telescope commit: 9e76b16

### Min init.vim

```viml
set nocompatible hidden laststatus=2
set rtp+=/home/kristijan/.config/nvim/pack/packager/start/popup.nvim
set rtp+=/home/kristijan/.config/nvim/pack/packager/start/plenary.nvim
set rtp+=/home/kristijan/.config/nvim/pack/packager/start/telescope.nvim

lua << EOF
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF

```

Gif:
telescope-bat

### PR DESCRIPTION
**Pull request by glepnir**
close #488  @kristijanhusak can you test this patch ? If works fine. I will merge.

cc @Conni2461

### CODE REVIEW

**Review by Conni2461 — APPROVED** [review]
Thanks :) LGTM
I was to lazy to open a PR 🤣

**Comment by glepnir** [comment]
@Conni2461  haha It's ok. I also got this problem

**Comment by Conni2461** [comment]
You have to use the buffer_previewers 😆 as core member :D Didn't the contract mention that 🤣

**Comment by glepnir** [comment]
@Conni2461  I had changed to  `file_previewer = require'telescope.previewers'.vim_buffer_cat.new` ,there has a question .

If we lazyload treesitter with plugin mangement. and use telescope in dashboard . use find_files. got built in syntax.

**Comment by Conni2461** [comment]
Oh that was fixed last week or so https://github.com/nvim-telescope/telescope.nvim/pull/479 :)

Also feel free to merge that PR if everything still works but could you add:
continuation of https://github.com/nvim-telescope/telescope.nvim/commit/9e76b1613a25cc6f63d17eb73432523924662619

in the additional commit description. thanks :)

**Comment by glepnir** [comment]
Not a big problem, only when used for the first time  if  use rtp's plugin manager, #479 does not wor

**Comment by Conni2461** [comment]
Okay merge that PR that PR works 😆 
And then write me on gitter in private. Maybe we can do some debugging 😆 but this PR is not the right place :)

**Comment by glepnir** [comment]
yep . I had check #298 and have some idea.

**Comment by kristijanhusak** [comment]
@glepnir works great, thanks!

**Pull request merged**
