### PR TITLE
Fix folding when a file is opened

### LINKED ISSUE #559: Opening files leads to problems with restoring views and treesitter
### Description
When I open a file from telescope, views aren't restored (e.g. cursor position, folds) and tree-sitter highlighting isn't used. Instead syntax highlighting is used. I can't create new folds either.

**Expected Behavior**
When I open a file from telescope, views should be restored in the same way as when I open a file directly. Treesitter should be enabled just as it is when normally opening a file.

**Actual Behavior**
Views aren't restored and treesitter isn't used. In order to get treesitter to work correctly and my views restored, I need to reload the buffer (`:e`) after opening the file. If I do just `:loadview` my view is restored, but treesitter highlighting is not. You can see that `:e` restores treesitter highlighting as doing `:syntax` before will give you the syntax items, whereas after `:e` it gives `No Syntax items defined for this buffer`.

### Details

<details><summary>Reproduce</summary>

1. open some file with folding and tree-sitter highlighting (e.g. a lua file) 
2. Move the cursor, open/close some folds
3. close nvim
4. run nvim
5. open telescope with e.g. `:Telescope find_files`
6. search for previous file and open it
</details>

<details><summary>Environment</summary>

- nvim --version: NVIM v0.5.0-dev+1109-g6b7cc45c4
- Operating system: Latest Arch Linux
- Telescope commit: e2696d6

</details>

<details><summary>Configuration</summary>
<p>

```viml
if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'} "treesitter
Plug 'zhimsel/vim-stay' "restore settings
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}

require'nvim-treesitter.configs'.setup({
  ensure_installed = "maintained",     -- one of "all", "maintained", or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    disable = {},               -- list of language that will be disabled
  },
})

EOF

" folding
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()

" view restore
set viewoptions=cursor,folds,slash,unix
```

### LINKED ISSUE #699: File opened with Telescope: find_files can't be folded (E490: No fold found)
### Description
Opening file with Telescope: find_files  - makes it so that opened file can be folded. I use TreeSitter for folding :

```
vim.wo.foldmethod="expr"
vim.o.foldexpr="nvim_treesitter#foldexpr()"  
vim.wo.foldenable=false -- can be enabled directly in opened file - using 'zi' - toogle fold

```
The error when I try to fold - E490: No fold found
**Expected Behavior**
Opened files using :e  File.py , or NvimTree  can be folded ok.

**Actual Behavior**
The error when I try to fold - E490: No fold found
I can fix it by reloading file-  :e %

### Details
Steps to reproduce

- : Telescope find_files
- open file
- use hotkey: zc (close fold)   - in my case I have to use 'zi' hotkey to enable folding first.

My basic fold setup:
```
vim.wo.foldmethod="expr"
vim.o.foldexpr="nvim_treesitter#foldexpr()"  
vim.wo.foldenable=false -- can be enabled directly in opened file - using 'zi' - toogle fold
```
Treesitter:

```
local ts_config = require("nvim-treesitter.configs")

ts_config.setup {
    ensure_installed = {
        "html",
        "css",
        "bash",
        "python",
        "lua"
    },
    highlight = {
        enable = true,
        use_languagetree = true
    },
	indent = {enable = true},
    -- playground = {
    --     enable = true,
    --     disable = {},
    --     updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    --     persist_queries = false -- Whether the query persists across vim sessions
    -- },
    autotag = {enable = true},
    rainbow = {enable = true},
} 
```

and Telescope:
```
require("telescope").setup {
    defaults = {
        vimgrep_arguments = {
            "rg",
            "--color=never",
            "--no-heading",
            "--with-filename",
            "--line-number",
            "--column",
            "--smart-case"
        },
        prompt_position = "bottom",
        prompt_prefix = " ",
        selection_caret = " ",
        entry_prefix = "  ",
        initial_mode = "insert",
        selection_strategy = "reset",
        sorting_strategy = "descending",
        layout_strategy = "horizontal",
        layout_defaults = {
            horizontal = {
                mirror = false,
                preview_width = 0.5
            },
            vertical = {
                mirror = false
            }
        },
        file_sorter = require "telescope.sorters".get_fuzzy_file,
        file_ignore_patterns = {},
        generic_sorter = require "telescope.sorters".get_generic_fuzzy_sorter,
        shorten_path = true,
        winblend = 0,
        width = 0.75,
        preview_cutoff = 120,
        results_height = 1,
        results_width = 0.8,
        border = {},
        borderchars = {"─", "│", "─", "│", "╭", "╮", "╯", "╰"},
        color_devicons = true,
        use_less = true,
        set_env = {["COLORTERM"] = "truecolor"}, -- default = nil,
        file_previewer = require "telescope.previewers".vim_buffer_cat.new,
        grep_previewer = require "telescope.previewers".vim_buffer_vimgrep.new,
        qflist_previewer = require "telescope.previewers".vim_buffer_qflist.new,
        -- Developer configurations: Not meant for general override
        buffer_previewer_maker = require "telescope.previewers".buffer_previewer_maker
    },
    extensions = {
        media_files = {
            filetypes = {"png", "webp", "jpg", "jpeg"},
            find_cmd = "rg" -- find command (defaults to `fd`)
        }
    }
}

require("telescope").load_extension("media_files")

local opt = {noremap = true, silent = true}

vim.g.mapleader = " "

-- mappings
vim.api.nvim_set_keymap("n", "<Leader>ff", [[<Cmd>lua require('telescope.builtin').find_files()<CR>]], opt)
vim.api.nvim_set_keymap( "n", "<Leader>fp", [[<Cmd>lua require('telescope').extensions.media_files.media_files()<CR>]], opt)
vim.api.nvim_set_keymap("n", "<Leader>fb", [[<Cmd>lua require('telescope.builtin').buffers()<CR>]], opt)
vim.api.nvim_set_keymap("n", "<Leader>fh", [[<Cmd>lua require('telescope.builtin').help_tags()<CR>]], opt)
vim.api.nvim_set_keymap("n", "<Leader>fo", [[<Cmd>lua require('telescope.builtin').oldfiles()<CR>]], opt)
vim.api.nvim_set_keymap("n", "<Leader>fm", [[<Cmd> Neoformat<CR>]], opt)
```

### PR DESCRIPTION
**Pull request by abelmul**
fix #559 
fix #699 

As outlined [here](https://github.com/nvim-telescope/telescope.nvim/issues/559#issuecomment-1002803413) the reason for #559 is not leaving insert mode when opening the file.

This just wraps the opening logic in autocmd InsertLeave

### CODE REVIEW

**Comment by Conni2461** [comment]
This patch will make problems for anything that has line or col information. Some examples are live_grep, grep_string, ...

But thanks for finding the root cause of that issue. Well done :)

**Comment by abelmul** [comment]
yeah didn't notice that. Is there any other way to wait for insert leave?

**Comment by abelmul** [comment]
I tried to find what caused the `stopinsert` to wait that long but couldn't find anything

**Comment by Conni2461** [comment]
I cleaned up your folding fix a little bit. Does this work for you ?

**Comment by abelmul** [comment]
Yes it does.

**Comment by abelmul** [comment]
In case you are wondering though the `stopinsert` doesn't work because of some autocmds that don't finish before opening the file. See [this](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/pickers.lua#L502)

**Comment by Conni2461** [comment]
lets see what happens

Thanks for the fix :)

**Comment by GreatestOfAllTimee** [comment]
It's seems like after this commit I was not able to open files using `:Telescope find_files`. I don't quite sure if this is from Telescope itself or my config setup.

**Is it happen before this ?** _No_.

E.g :

- `:Telescope find_files`
- Select file and enter.
- return nothing.
- Try call `:Telescope find_files` _again_ and return error.

telescope

**Comment by Conni2461** [comment]
I just tried to reproduce with 0.6.1 and with the latest nightly release. With my own config and our minimal rc and couldn't reproduce. :disappointed: 

Could you open a real bug report, which will provide me with more information?

**Comment by samr** [comment]
I am also not able to open files with this fix. I am seeing a similar but slightly different error message on both 0.6.1 and the latest nightly. I too am not sure if it is something specific to my set up.

image

I fixed it by adding back the old way of calling files to set.lua, on ~line 135...
```
    if vim.api.nvim_buf_get_name(0) ~= filename or command ~= "edit" then
      filename = Path:new(vim.fn.fnameescape(filename)):normalize(vim.loop.cwd())
      -- Make sure we wait till we are back in insert mode before opening the file
      -- This fixes foldes

      -- Commented out because this is broken. Introduced in https://github.com/nvim-telescope/telescope.nvim/pull/1643/files
      -- vim.cmd(string.format(
      --   [[%s :lua require("telescope.actions.utils").__open_file_at("%s", "%s", %s, %s)]],
      --   "autocmd InsertLeave * ++once ++nested", -- open file as soon as we have left insert mode (fixes folding)
      --   command,
      --   filename,
      --   row,
      --   col
      -- ))

      -- My hacky fix
      pcall(vim.cmd, string.format("%s %s", command, filename))
      if row and col then
        local ok, err_msg = pcall(a.nvim_win_set_cursor, 0, { row, col })
      end
    end
```

**Comment by Conni2461** [comment]
Okay revert for now. Sadge

**Comment by Conni2461** [comment]
I'll go searching for a different solution. Maybe we need to rewrite our shutdown: https://github.com/nvim-telescope/telescope.nvim/pull/1643#issuecomment-1007638766

**Pull request merged**
