### PR TITLE
Advanced normal mode

### LINKED ISSUE #466: feat: Normal mode: Walking multiple steps at once (ie 5j or 5k)
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to type single j and k to walk inside the editor, so I always do 5j,5k etc for navigation.
However, in normal mode I can not use 5j or 5k to walk 5 steps down and up.

**Describe the solution you'd like**
I would like to have the same walking behavior like (neo)vim, wher you can use 5j and 5k (after changing to normal mode) for walking 5 steps down and up.

**Describe alternatives you've considered**
I think the default behavior of neovim should be represented, if feasible, to reduce learning or configuration need.

### PR DESCRIPTION
**Pull request by Conni2461**
Close #466

Ref #403
Works only for the current screen because we can not yet scroll through all results.
Sorry it take me that long

- [x] `<count>j` and `<count>k`
- [x] G and gg (doing that tomorrow)

CC @hoob3rt

### CODE REVIEW

**Comment by Conni2461** [comment]
Okay that should be good now. I was thinking maybe we could use the `scroller` for `top` and `bottom` but i need to look at that one first. Also maybe `H` and `L` are better mappings rather than `G` and `gg`?! Maybe we can add `G` and `gg` later if we have scrolling?!

Also @tjdevries should we merge that before https://github.com/nvim-telescope/telescope.nvim/pull/472 or after. If before i take a look at the `scroller` much sooner. Also depends on what the people demand 🤣

**Comment by Conni2461** [comment]
Its mapped to `H` and `L` now. It would be done. @tami5 probably does some testing first tho

**Comment by tami5** [comment]
Works very well, is there way to map it in normal mode, maybe \<c-s-l\>/\<c-s-h\>. Also `G` and `g` maybe be more generic and `<c-g>/<c-G>`

**Comment by Conni2461** [comment]
Sure you can map it in insert mode:
```lua
mappings = {
  i = {
    ["<c-h>"] = actions.move_to_top,
    ["<c-l>"] = actions.move_to_bottom,
  },
},
```
But you can't map `<c-g>` and `<c-G>` because ctrl and ctrl_shift is the same.

Will add some tests then ask tj

**Pull request merged**
