### PR TITLE
Add test ci

### PR DESCRIPTION
**Pull request by Conni2461**
It actually runs: https://github.com/Conni2461/telescope.nvim/actions/runs/409082452

### CODE REVIEW

**Comment by tjdevries** [comment]
I have changed plenary.nvim setup & execution. No more dependencies. We can chat about it tomorrow perhaps if you don't solve it before I'm awake.

**Comment by Conni2461** [comment]
Works now almost out of the box. Tested it with no luarocks setup and `say` was missing. After installing that with: `luarocks install --lua-version 5.1 --local say` everything worked as expected. Thanks for updating it :)
https://github.com/Conni2461/telescope.nvim/runs/1522350679?check_suite_focus=true

**Comment by tjdevries** [comment]
I'm wondering if we even need the first thing on ubuntu... It takes a LONG time to build nvim from scratch. So maybe we can just do that only for mac or something (and maybe only on master or something... I don't know how many free minutes I get per open source repo)

**Comment by tjdevries** [comment]
You can merge whenever you're ready, we can tinker with it more later!

**Pull request merged**
