### PR TITLE
[RFC] Fix help_tags previewer

### PR DESCRIPTION
**Pull request by parmort**
Continuation of #230.
I don't use previews, which explains why I didn't include this in the original PR.

### CODE REVIEW

**Comment by sunjon** [comment]
There's some debug output left in the PR; current selection is being echoed to  the command line.
`print(vim.inspect(new_bufnr))` in builtin.lua.
Other than that, LGTM!

**Comment by sunjon** [comment]
There's still one more line outputting unnecessarily to the command line:
previewers.lua:472

I don't _think_ it's necessary to output the current selection or chosen selection for any of the finders, but in tracking down what was emitting this, I did notice a few `print(vim.inspect)` and `print()`s that seem to be only there for debug purposes. I'll make a PR to remove them.

**Review by sunjon — COMMENTED** [review]
works great now. Thanks

**Comment by Conni2461** [comment]
Thanks for fixing this @parmort 

@sunjon I think we should squash and merge PRs like tjdevries

**Comment by tjdevries** [comment]
Yes, please squash & merge and give merge a helpful commit message. Thanks! :)

**Comment by sunjon** [comment]
Ah apologies, forgot about that.

**Comment by tjdevries** [comment]
No problem :)

**Pull request merged**
