### PR TITLE
feat: Add optional native compilation step

### PR DESCRIPTION
**Pull request by tjdevries**

### CODE REVIEW

**Comment by tjdevries** [comment]
TODO:
- Proper attribution
- Readme updates
- Better native switching
- Might add re-using the matches as well... we'll see. Positions is not called for every match (but we could cache within one run)

**Comment by tami5** [comment]
How can I test this, what additional steps to take? thanks @tjdevries

**Comment by tjdevries** [comment]
I think I will implement extensions this week. Then I will implement fzy-native as an extension (it will be as easy as installing the repo with an installation step most likely to compile). 

Then you should be able to use fzy-native and it will be very fast :)

**Comment by tami5** [comment]
@tjdevries looking forward for posting performance. as I intend to filter through a huge list of files . Thanks

**Comment by tjdevries** [comment]
I actually did a readme update that shows how to do this the other way now. We made a new repo for this

**Pull request closed without merging**
