### PR TITLE
doc: help for select_{default,tab,vertical,horizontal}

### LINKED ISSUE #1799: Documentation for `select_*` actions
#### Is your feature request related to a problem? Please describe.
As it currently stands `select_default` `select_vertical` and `select_horizontal` don't appear to have any documentation in the actions section of the help file.

#### Describe the solution you'd like
Add documentation for these under `telescope.actions`

#### 
Maybe there is a more appropriate place for their documentation I don't know about.

### PR DESCRIPTION
**Pull request by cafce25**
Resolves #1799

Attempt number 2 hopefully added the docs in the correct place this time around '-.-

### CODE REVIEW

**Comment by cafce25** [comment]
I generated the docs that result from this and `docgen` rips apart the code blocks since they make the line slightly too long. I think that's a bug?! But I would have no idea where to file it (here?, tjdevries/tree-sitter-lua?).

The other question is, can I somehow instruct docgen to generate a single newline only?
An empty doc comment line results in an empty line (= 2 newlines) in the docs.

**Comment by Conni2461** [comment]
no its not a bug. we dont take ` into consideration and only strictly try to follow 78 line length. You can do manually break lines with `<br>` at the end of the line

**Comment by Conni2461** [comment]
I pretty much documented everything here: https://github.com/tjdevries/tree-sitter-lua/blob/master/HOWTO.md

Thanks for your PR :)

**Comment by cafce25** [comment]
I see, maybe ` should be taken into account since it does have special meaning for vim help files. Anyways, I adjusted the code and it renders ok now i think.

**Comment by cafce25** [comment]
> I pretty much documented everything here: https://github.com/tjdevries/tree-sitter-lua/blob/master/HOWTO.md

That's the documentation I was missing, thanks!

**Review by Conni2461 — APPROVED** [review]
LGTM thanks :)

We can support it but it might be its not that high on my todo list because `<br>` is a valid workaround for this issue. If you'd like support feel free to open a issue over at https://github.com/tjdevries/tree-sitter-lua

**Pull request merged**
