### PR TITLE
fix: check if caret is present before removal

### LINKED ISSUE #1389: Non standard caret makes first characters disappear in selection window
### Description

Set selection_caret to more than 2 characters ('>>' for example) or non-ASCII character.

Open a picker, start typing to filter results.

Some results inside selection window get their first characters cut off.

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/neovim-0.5.1/build/config -I/builddir/neovim-0.5.1/src -I/usr/include -I/builddir/neovim-0.5.1/build/src/nvim/auto -I/builddir/neovim-0.5.1/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

VoidLinux-musl

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `project`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. get the minimal config below
2. open find_files
3. start filtering out

I found a simpler case: use `:Telescope filetypes`, type `yam` then delete `m`. The 2nd prompt (should be `yaml`) will only be shown as `ml`

### Expected behavior

No characters are cut off in the selection window.

### Actual behavior

First characters are cut off in some results.

In the image below it was the `util.lua` file name in the 2nd selection.

image

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup {
    defaults = {
      selection_caret = '>> ' -- more than 1 characters
      -- selection_caret = '🐱 ' -- an emoji or a nerd font symbol
    }
  }
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by l-kershaw**
Resolves #1389

@FollieHiyuki does this fix things for you?

### CODE REVIEW

**Comment by FollieHiyuki** [comment]
I tried to set the caret to ' ' (`nf-fa-chevron_right` from nerd-fonts) which takes the width of 1 (plus 1 width for the blank space). But it seems to delete the previous caret with 3 beginning characters.

screenshot

**Comment by FollieHiyuki** [comment]
Maybe it just the glyph that makes it unable to detect width. If that is the case I can live with it.

Setting the caret to multiple normal characters doesn't cause issue now.

**Comment by l-kershaw** [comment]
Hmmm... am a bit confused

@FollieHiyuki does this work better?

**Comment by FollieHiyuki** [comment]
Thanks. It works ok now. I haven't spotted anything wrong for couple of hours :)

**Review by Conni2461 — APPROVED** [review]
I think that makes sense. I havent tested it thought so if it is confirmed working, feel free to merge l-kershaw.

Thanks :)

make sure to change the commit message, `strdisplaywidth` isnt up to date anymore :)

**Pull request merged**
