### PR TITLE
support convert custom command arg

### PR DESCRIPTION
**Pull request by glepnir**
support #437

### CODE REVIEW

**Comment by glepnir** [comment]
@delphinus  Does this can work for you?

**Comment by Conni2461** [comment]
Works for me :) Thanks

**Comment by tami5** [comment]
Nice @glepnir , I love how powerful this is becoming

**Comment by delphinus** [comment]
confirmed. It does all good. thx!

**Comment by glepnir** [comment]
Ok Now merged.

**Comment by MuhammedZakir** [comment]
A doubt:

```
    ['boolean'] = function(key,val)
      if val == 'false' then
        user_opts[key] = false
      end
      user_opts[key] = true
    end,
```

From what I understand, the `user_opts[key] = true` statement is executed regardless of `val`'s value? Shouldn't this be a if-else conditional for this to work correctly?

```
    ['string'] = function(key,val)
      if val == 'nil' then
        user_opts[key] = nil
      end
      if val == '""' then
        user_opts[key] = ''
      end
      if val == '"' then
        user_opts[key] = ''
      end
      if bool_type[val] ~= nil then
        user_opts[key] = bool_type[val]
      end
    end
```

Isn't if-elseif better for this? Not that this is wrong, but I feel like it's redundant as each if block is executed at the moment even when it doesn't need to. For example, if `val` is `nil`, there is no need to execute subsequent statements.

**Comment by glepnir** [comment]
I  had rewrire this in my local branch.  make pr later. but don't use if else. too many if else will increase cycle complexity of code

**Comment by MuhammedZakir** [comment]
> I had rewrire this in my local branch. make pr later

Okay! :-)

> but don't use if else. too many if else will increase cycle complexity of code

You're right about that. I assume you're talking about second one, right? But, the code already have those if conditionals. I personally think changing it to `if-elseif` makes it easier to read/debug because if one `if` statement is matched, you can ignore all other `if` branches. That's not the case with current code/style. This is my personal option. So I maybe wrong, and to be honest, for this one, it's probably very easy to know we only need to care about one `if` conditional.

**Pull request merged**
