### PR TITLE
feat: the parameter "map" of attach_mappings can be list of modes to create mapping on multiple modes

### PR DESCRIPTION
**Pull request by adoyle-h**
# Description

like vim.keymap.set

Example:

```lua
attach_mappings = function(prompt_bufnr, map)
  map({ 'i', 'n' }, '<C-r>', function() end)
end
```

and refactor: merge map("i") and map("n") into map({"i", "n"}) in telescope/builtin

## Type of change

- New feature (non-breaking change which adds functionality)

**Configuration**:
* Neovim version (nvim --version):

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

* Operating system and version:

MacOS 12.2 (Apple M1 Pro)

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

**Comment by Conni2461** [comment]
LGTM thanks :) do we want to use this interface for our builtins? to cleanup some code?

Like everywhere we are doing this
https://github.com/nvim-telescope/telescope.nvim/blob/4bd4205028d6588cf2e0a1346687a6039b0f0a7c/lua/telescope/builtin/__git.lua#L74-L75

**Comment by adoyle-h** [comment]
@Conni2461 Done.

**Review by Conni2461 — APPROVED** [review]
Thanks :)

**Comment by Conni2461** [comment]
I'll fix ci and generate docs after that i merge

**Pull request merged**
