### PR TITLE
fix: update themes after `layout_strategies` refactor

### PR DESCRIPTION
**Pull request by l-kershaw**
Adjust the sizing options for themes since [this PR](https://github.com/nvim-telescope/telescope.nvim/pull/1039) has been merged.

Discussed in comments of the PR starting [here](https://github.com/nvim-telescope/telescope.nvim/pull/1039#issuecomment-922489474).

### CODE REVIEW

**Review by Conni2461 — APPROVED** [review]
Thanks :)

**Comment by l-kershaw** [comment]
@Conni2461 I'm away from my PC, so feel free to merge

**Comment by windwp** [comment]
@l-kershaw with this update theme dropdown and ivy is broken

**Comment by Conni2461** [comment]
@windwp Shouldnt be broken, make sure you have a up to date plenary version

**Comment by windwp** [comment]
@Conni2461 yeah my bad.

**Pull request merged**
