### PR TITLE
feat: smart send to qflist

### PR DESCRIPTION
**Pull request by Conni2461**
Is this `smart_send` useful to anyone otherwise i remove it from this PR. Basically what it does it sends all to qflist if nothing multi-selected otherwise send multi selected. I am using it since 3 days and thought i can just upstream it. :)

Also:
- scrolling is half window height because its bothering me for quite some time
- Remove some stuff from readme and fix that experimental default previewer mistake

### CODE REVIEW

**Comment by elianiva** [comment]
what a coincidence, I was about to submit a PR about the scrolling speed because I can't stand it anymore :rofl:
do we want it to be customisable though? mine has an option for that on `layout_defaults` and uses `math.floor` because apparently it freaks out when it receives a float value (like, it inserts some random characters to the previewer for some reason)
if not, we could use yours

**Comment by Conni2461** [comment]
Feel free to checkout this branch and finish it, i currently don't have time to add config value as well. Just open a new PR and close this one, i don't need the commit :) 

`math.floor(lines / 2)` I also had a floor.

**Comment by elianiva** [comment]
> math.floor(lines / 2) I also had a floor.

ok how did I miss that haha, I guess I should've gone to sleep instead of fixing this annoying thing 😆 
will continue to work on that tomorrow

**Comment by elianiva** [comment]
#610

**Pull request closed without merging**
