### PR TITLE
fix: for telescope.symbols

### LINKED ISSUE #1072: Actions.insert doesn't behave as expected
I am playing around with `Telescope symbols` and noticed the following unexpected behavior when using it in insert mode (which is the most common use, I'd say):

1. `:inoremap <c-s> <cmd>Telescope symbols<cr>`
2. type `foobar`
3. place the cursor between `foo` and `bar`
4. trigger `<c-s>` and insert any symbol, say, `X`

**Expected**: `fooX|bar` in insert mode

**Actual**: `foob[X]ar` in normal mode

(Also, wouldn't a better place for sources be in `.local/share/nvim/telescope/symbols` rather than under `.config`? I feel there could be a general "data cleanup" for `telescope_history` and `file_frecency.sqlite3` as well...)

### PR DESCRIPTION
**Pull request by Conni2461**
Closes #1072

- keep insert
- also look in `.local/share/nvim/telescope/symbols/*.json` for symbols
  can be overriden with `symbol_path`

The only thing that is currently bothering me is that you end up in insert mode even if you started in normal mode. 
- Done this with actions `:enhance` good interface

CC @clason better late than never :rofl:

### CODE REVIEW

**Comment by Conni2461** [comment]
clason should be ready for testing if you find some time :) 
We will end up in the mode we started. This is currently only happening for `symbols` but maybe we should actually write a interface for that at some point.
Symbols can also be put in `stdpath("data")/telescope/symbols/*.json` now, more information in the docs :)

**Comment by clason** [comment]
Hmm, that still puts the symbol _before_ the cursor if it is at the end of a line?

**Comment by clason** [comment]
Also, in normal mode the cursor moves, which I don't think is the expected behavior? Or maybe it is (behaving like `p`)?

**Comment by Conni2461** [comment]
Late night programming is never good :rofl: 

This is kinda annoying we wanna do two different things based on if we started in normal mode or if we started in insert mode. No one is currently using this so i can technically do what i want: https://sourcegraph.com/search?q=context:global+insert_symbol+lang:lua&patternType=literal

You can try the lastest commit which should work, (`P` in normal). Maybe i do two actions one for when starting in normal mode, which is the implementation we have in master and a new action that should be triggered if started in insert mode.

**Comment by clason** [comment]
Also, don't drink and develop! :)

That seems to work now, thank you! Yes, two different (internal) mappings sounds reasonable.

**Comment by Conni2461** [comment]
only coffee is allowed while coding :)

yeah its `p`, i dont know  what i am even saying anymore :rofl: so this pr shouldn't change the current normal mode behavior but fixes insert mode.

**Comment by clason** [comment]
@Conni2461 anything left you want to do here? Or should I go ahead and merge?

**Comment by Conni2461** [comment]
I think this should be good.

**Pull request merged**
