### PR TITLE
feat: Patch sorting popup autocomplete items and initial builtin items

### PR DESCRIPTION
**Pull request by 03juan**
# Description

I noticed that neovim wasn't sorting the list of autocomplete items when pressing tab in the command line.

In my very limited lua + nvim knowledge, there doesn't seem to be a way to create an autocommand that intercepts the completion list in the command popup.

So I decided to try my hand at brute-forcing the solution from telescope's side.

Here I sort the list of available commands for each of the 4 possible code paths.

The initial builtin list is also unsorted.

Let me know if this is useful or if you have any other recommendations for sorting the options. It's also ok if this feature is not wanted. 👍

(I messed up and renamed the branch on the closed PR #2515 not knowing GH would close it. Sorry for the double submission)

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

- [x] Various `print` commands to ensure I hit all 4 paths.
image
- [x] Testing the autocompletions manually and ensuring no errors or unexpected suggestions.
- [x] `n == 0`
image
- `:Telescope <Tab>`
  - Before:
  image
  - After:
  image
- `:Telescope l<Tab>`
  - Before:
  image
  - After:
  image

- [x] `n == 1 and #is_extension > 0`
image
- `:Telescope gh <Tab>`
  - Before:
  image
  - After:
  image

- [x] `n == 1 and #is_extension == 0`
image
- `:Telescope autocommands <Tab>`
  - Before:
image
  - After:
image

- [x] `n > 1`
image
- `:Telescope autocommands wrap_results <Tab>`
  - Before:
image
  - After:
  image

- `:Telescope gh issues <Tab>`
  - Before:
image
  - After:
image

- [x] Builtin list
Left: Before
Right: After
image

All tests pass on the fork ✅

**Configuration**:
* Neovim version (nvim --version): 0.9.0
* Operating system and version: Ubuntu 22.04 in WSL2 on Windows 11

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

**Comment by Conni2461** [comment]
thanks :) i just merged another branch into master and it looks like you need to rebase/merged master in again, sorry.

If you want i could resolve it

**Comment by 03juan** [comment]
Yes please, I'm not that great with git. Go ahead and rebase/squash as you see fit :)

**Comment by Conni2461** [comment]
thanks :)

**Comment by 03juan** [comment]
I'll be sure to format with stylua locally before pushing in the future!

**Pull request merged**
