### PR TITLE
feat(lsp): added support for dynamic capabilities

### PR DESCRIPTION
**Pull request by folke**
# Description

Added support for dynamic registration of capabilities to all the lsp pickers.
I also refactored the relevant code a bit to make it less verbose.

Any code that wants to check lsp capabilities should use `client.supports_method`.
That function includes checks for dynamically registered capabilities.
Just checking `server_capabilities` only includes caps that were advertised during init.

Fixes https://github.com/LazyVim/LazyVim/discussions/990

Fixes `goto definition` for a number of lsp servers like `jdtls` and `solargraph`

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I've testes all the methods using several LSP servers including the one `solargraph` where go to definition was broken.

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

**Comment by folke** [comment]
The failing tests are not because of this change, but because homebrew can not be updated

**Comment by tjdevries** [comment]
Thanks, makes sense to me. Some of that LSP code is quite old (not all the methods existed at the time). Thanks :)

**Comment by ben-krieger** [comment]
Is there a reason that this commit hasn't been cherry-picked into a release (of which there have been a few since the PR was merged)? The README discourages using `master`, but as a user of `jdtls`, I need this fix for jumping to definition to work.

**Comment by jamestrew** [comment]
@ben-krieger we aren't cherry picking features into 0.1.x following semver. This will come in 0.2.0 but no timeline for this.
Best bet is using the master branch pinned to this commit.

**Pull request merged**
