### PR TITLE
fix: nightly removal of vim.lsp.util._str_byteindex()

### PR DESCRIPTION
**Pull request by tris203**
This will be required when/if https://github.com/neovim/neovim/pull/30915 is merged

Ping @clason

### CODE REVIEW

**Comment by clason** [comment]
Is this backward compatible? Telescope still supports Nvim 0.9.

**Comment by tris203** [comment]
> Is this backward compatible? Telescope still supports Nvim 0.9.

Yes, it should be. I tested with 0.10 and the same function is present in 0.9
https://github.com/neovim/neovim/blob/0ef27180e31671a043b28547da327cd52f1a87c4/runtime/lua/vim/lsp/util.lua#L155

**Comment by wojciech-kulik** [comment]
It looks like this commit broke jump to definition. My binding:
```
      keymap.set("n", "gd", "<cmd>Telescope lsp_definitions trim_text=true<cr>", opts)
```

Error:
```
Error executing vim.schedule lua callback: ...nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:108: bad argument #2 to 'str_byteindex' (number expected, got string)
stack traceback:
        [C]: in function 'str_byteindex'
        ...nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:108: in function 'item_to_location'
        ...nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:244: in function 'handler'
        ...-nightly/nvim-nightly/share/nvim/runtime/lua/vim/lsp.lua:941: in function 'handler'
        ...y/nvim-nightly/share/nvim/runtime/lua/vim/lsp/client.lua:681: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by clason** [comment]
What is your Nvim version?

**Comment by wojciech-kulik** [comment]
Oh, you're right, maybe it's because I'm using nightly:
```
NVIM v0.11.0-dev-1016+gca7855c5b
```

**Comment by tris203** [comment]
> Oh, you're right, maybe it's because I'm using nightly:
> 
> ```
> NVIM v0.11.0-dev-1016+gca7855c5b
> ```

Take your nightly to HEAD and it should work

**Comment by wojciech-kulik** [comment]
Thank you! Now it works, it turned out that my nix config was caching nightly build that's why I didn't get the latest version. So accidentally it helped me solved that hidden issue :)

**Pull request merged**
