### PR TITLE
docs: update outdated gif + more demo

### PR DESCRIPTION
**Pull request by elianiva**
We now use buffer previewer as the default, might as well update the readme demo. Also, I'll add the rest of the builtins demo for the wiki later

### CODE REVIEW

**Comment by tami5** [comment]
@elianiva it looks really nice, I like the colors schema what is it?

Also can you please reproduce other pickers showed in the last gif as it's showcases different use cases of telescope

**Comment by elianiva** [comment]
I think I'll add a link that points to the wiki for more detailed demo later, that'd be better than waiting the gif to be played repeatedly IMO

btw, the colourscheme is https://github.com/embark-theme/vim
I only use it for the demo :laughing:

**Comment by elianiva** [comment]
Here's a list of the ones I've done so far (will add them to wiki once I've made all of them)

- [x] builtin.find_files
- [x] builtin.git_files
- [x] builtin.grep_string
- [x] builtin.live_grep
- [x] builtin.file_browser
- [x] builtin.buffers
- [x] builtin.oldfiles
- [x] builtin.commands
- [x] builtin.tags
- [x] builtin.command_history
- [x] builtin.help_tags
- [x] builtin.man_pages
- [x] builtin.marks
- [x] builtin.colorscheme
- [ ] builtin.quickfix
- [ ] builtin.loclist
- [x] builtin.vim_options
- [ ] builtin.registers
- [x] builtin.autocommands
- [ ] builtin.spell_suggest
- [x] builtin.keymaps
- [x] builtin.filetypes
- [x] builtin.highlights
- [x] builtin.current_buffer_fuzzy_find
- [x] builtin.current_buffer_tags	Lists
- [x] builtin.treesitter
- [x] builtin.lsp_references
- [x] builtin.lsp_document_symbols
- [x] builtin.lsp_workspace_symbols
- [ ] builtin.lsp_code_actions
- [ ] builtin.lsp_range_code_actions
- [x] builtin.git_commits
- [x] builtin.git_bcommits
- [x] builtin.git_branches
- [x] builtin.git_status
- [ ] builtin.planets
- [x] builtin.builtin
- [x] builtin.reloader
- [x] builtin.symbols

**Comment by Conni2461** [comment]
Seems like a good idea to add gifs for each builtin into the wiki.
We can merge this if the PR is done :)

(Did you showcase the file creation with `file_browser` :smile: )

**Comment by elianiva** [comment]
> (Did you showcase the file creation with file_browser smile )

of course, how could I not include it when it is so *awesome* :laughing:

**Comment by elianiva** [comment]
I'm pretty much done, just need to convert all of them to gif and add it to the wiki. I couldn't do the last 3 previewers because 
- I don't know how to use `builtin.range_code_actions` or `builtin.quickfix` :laughing: 
- `builtin.registers` throws an error saying it's not possible to have this many results or something like that

**Comment by Conni2461** [comment]
- For quickfix: Just use `actions.send_to_qflist` and then open `Telescope quickfix`. Also a really good showcase of an amazing feature.
- For range_code_actions never worked for me as well. But if nobody reports it its not a BUG :rofl: 
- for registers @sunjon your features are not working :D

**Comment by elianiva** [comment]
I've added them to the wiki https://github.com/nvim-telescope/telescope.nvim/wiki/Showcase
Let me know what you think. Some of them are converted to gif differently because I was using ffmpeg + imagemagick previously (for some reason, should've went with ffmpeg) until I realised that my laptop couldn't handle it so I moved to just using ffmpeg for the rest of them :laughing: 
Shouldn't be any difference though.

**Comment by tjdevries** [comment]
WOWOWOWOWOWOWOWOWOWOWOW Telescope has the best community :) Thanks for doing all of that elianiva :)

If you want a static place to host them as well, you can just drop them here https://github.com/tjdevries/media.repo :laughing: 

I use github as my media storage

**Comment by elianiva** [comment]
Alright then! I'll open a PR.

**Comment by elianiva** [comment]
It's safe to merge if anyone wants to merge this, I also fixed the link in the wiki to `tjdevries/media.repo` repo instead of my own so the current one is broken until TJ merge my PR. I gotta go now though :laughing:

**Comment by tami5** [comment]
@elianiva :heart: :heart: :heart: :pray:

**Pull request merged**
