### PR TITLE
Update Extensions README section

### PR DESCRIPTION
**Pull request by bi0ha2ard**
Thanks for the cool plugin!

I've created a picker for ROS and ROS2 workspace packages. Maybe someone finds it useful.

### CODE REVIEW

**Comment by Conni2461** [comment]
Thanks for using telescope, the kind words and for developing a extension :)

Now tbh i hate that section and i hate to be that guy that is complaining again :rofl:. It was cool back when we had like 2 extensions but now we are getting a PR for a new extension every other week. Don't get me wrong its super important that we display these extensions in some kind of way but i don't like them in the README anymore. We already have a section in the wiki that is a 1:1 copy see https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions

So here is what i am thinking we could do. You can rewrite this section (don't wanna take away your PR) to something that points to that wiki page. Really obvious so that everybody has to see it :laughing: and we make that page editable for all people.

We can also redesign the wiki page a little bit:
| Extension       | Description                |
|-----------------|----------------------------|
| fzy native link | Some elaborate description |

People can also get a bit more elaborate with what their extension tries to achieve. 

This isn't probably not the correct place to discuss that so sorry about that. Also i am looking for more opinions from members :D

**Comment by bi0ha2ard** [comment]
Thanks for your feedback.

I've added the extension to the list in the wiki (without touching the existing formatting) and replaced the community extension section in the README with a link to the page. I hope it's OK like this, otherwise, feel free to close the PR.

**Comment by Conni2461** [comment]
Thanks :) I'll keep it open for a day and wait for more feedback after that we can merge.

Could you also remove the `(not yet implemented)` and add the viml example of running extensions.
```viml
:Telescope dap configurations
```

**Comment by bi0ha2ard** [comment]
Done!

I've split it up a bit, but I wasn't 100% sure what to do with the "Pre-loading" example, so I just put that in its own subsection.

**Comment by Conni2461** [comment]
Maybe we should reformulate that to something like: "To load an extension do this" 

We still have lazy loading but with that `:Telescope` can't interpret the commands, so people should just always load it

**Comment by Conni2461** [comment]
Thats really really good thanks :)

**Comment by bi0ha2ard** [comment]
Ok that was quick, unfortunately I missed a typo, see #542

**Comment by Conni2461** [comment]
:laughing: Yeah i am currently going through some PR. Most of them are mine :laughing: Thanks

**Pull request merged**
