### PR TITLE
feat: Added "Silent" theme

### PR DESCRIPTION
**Pull request by torbratsberg**
Simple theme for quick operations where you barely need to look at the Telescope window.

### CODE REVIEW

**Comment by disrupted** [comment]
I like it, can imagine this really well for LSP code actions. Bonus points if we figure out how to place the popup relative to the current cursor location.

**Comment by torbratsberg** [comment]
@disrupted I agree! I couldn't find a way to set it relative to the cursor with the current configuration options, but that was the initial plan.

**Comment by Conni2461** [comment]
Isn't this just `require('telescope.themes').get_dropdown{ previewer = false }` with a different result_height? Also might be interesting for you but there is a huge refactor of how layouts work here: https://github.com/nvim-telescope/telescope.nvim/pull/823

**Comment by tjdevries** [comment]
Yeah, this seems _very_ close to the dropdown theme?

**Comment by torbratsberg** [comment]
It is very similar to the dropdown theme, but intended to be used for smaller and quicker actions. I just saw this PR #878 which has almost the same theme as Silent, but relative to the cursor which is probably a better layout for this kind of theme. So this PR can be closed.

**Comment by gokulsoumya** [comment]
> I like it, can imagine this really well for LSP code actions. Bonus points if we figure out how to place the popup relative to the current cursor location.

There's an open PR for cursor relative positioning - #878

**Pull request closed without merging**
