### PR TITLE
Fix typo in telescope.txt

### PR DESCRIPTION
**Pull request by dsychin**
There seems to be a typo in the themes section of the help text.

### CODE REVIEW

**Comment by fdschmidt93** [comment]
Thanks!

However, our vimdocs are auto-generated from EmmyLua annotations via https://github.com/tjdevries/tree-sitter-lua

Therefore, the typo would actually need to be fixed here

https://github.com/nvim-telescope/telescope.nvim/blob/e4ab6d28448747e7b0f922f5b8d2dbd63c24c176/lua/telescope/themes.lua#L11

and then CI will commit an update to reflect that change in the docs in your PR.

**Comment by dsychin** [comment]
Hi @fdschmidt93, I've updated the change.

**Comment by fdschmidt93** [comment]
docgen CI doesn't seem to be firing. I _think_ the fix is to go to `Settings->Actions->Check [] Allow all actions`.

**Comment by dsychin** [comment]
Hmm, it is already set to allow all actions.

image

**Pull request merged**
