### PR TITLE
fix(command_parser): pcall for the loadstring

### PR DESCRIPTION
**Pull request by l-kershaw**
Yet another fix for the command parser 😅 

Fixes [this comment](https://github.com/nvim-telescope/telescope.nvim/pull/1128#issuecomment-902682662)

@jonathannerat could you have a look/test this to make sure it works on your machine?

### CODE REVIEW

**Comment by l-kershaw** [comment]
I've added some tests that will hopefully stop me breaking this yet again in future 🤣

I want to add some more tests for other stuff that we parse (bools, numbers), but will do that tomorrow.
It would be helpful if people who are having issues with my latest commit could test this PR to make sure I'm not breaking anything else this time 😅

**Comment by jonathannerat** [comment]
Everything works from my side now, thank you!

**Review by Conni2461 — APPROVED** [review]
tests <3

its not a real feature if you dont need 3 fixup PRs :rofl: should i merge

**Comment by l-kershaw** [comment]
I have added more tests and tweaked things so that stuff with numbers like `:Telescope file_browser depth=2` works.

Regarding the `:Telescope` command issue, I think that was introduced in #1123, but @jonathannerat has come up with a nice solution in #1142.

Testing this PR + the changes from Jonathan's PR seems to fix all the problems that I am aware of, so will merge both now.

**Pull request merged**
