### PR TITLE
fix(pickers): misc inital_mode setting fixes

### LINKED ISSUE #1894: Insert mode is not set at startup when A is mapped
### Description

As was mentioned in the comments on this PR(#1886), when A is mapped, it doesn't start in insert mode by default.
@fdschmidt93

### Neovim version

```markdown
NVIM v0.8.0-dev+71-g188537efb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

ArchLinux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Telescope`
3. Not in insert mode.

### Expected behavior

When telescope is started, it will be set to insert mode.

### Actual behavior

When telescope is started, it does not set to insert mode.

### Minimal config

```Lua
vim.cmd [[syntax enable]]
vim.cmd [[filetype plugin indent on]]

local install_path = vim.fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
end
vim.cmd [[packadd packer.nvim]]

vim.keymap.set("n", "A", function()
        return vim.fn.len(vim.fn.getline(".")) ~= 0 and "A" or '"_cc'
end, { noremap = true, expr = true, silent = true })

return require('packer').startup(function()
  use {'wbthomason/packer.nvim', opt = true}
  use {'nvim-telescope/telescope.nvim',requires = { {'nvim-lua/plenary.nvim'} }, event = "VimEnter", config = function() require("telescope").setup({}) end}
end)
```

### PR DESCRIPTION
**Pull request by fdschmidt93**
Um, yeah, not gonna lie, this is satirically stupid but seems to work.

Importantly, this does not work appropriately if startinsert is invoked otherwise (`vim.cmd` or `vim.fn.execute`)

I think we can rely on `<ESC>` though :laughing:

Fixes:
- Code cleanup between initial modes `"normal"` and `"insert"`
- `initial_mode="normal"` wouldn't function properly if original mode was not `"normal"`
- `initial_mode="insert"`: raw input `startinsert!` to avoid `A` which might be mapped otherwise and cannot be fed with `nvim_feedkeys` (see code comments)

Closes #1894

### CODE REVIEW

**Comment by Conni2461** [comment]
image

**Comment by fdschmidt93** [comment]
No worries, I feel the same about this diff. It's a cursed fix and absurd that this works haha.

I'm not on my laptop today, will triple check tomorrow and then most likely merge :)

**Comment by fdschmidt93** [comment]
Fixes:
- Code cleanup between initial modes `"normal"` and `"insert"`
- `initial_mode="normal"` wouldn't function properly if original mode was not `"normal"`
- `initial_mode="insert"`: raw input `startinsert!` to avoid `A` which might be mapped otherwise and cannot be fed with `nvim_feedkeys` (see code comments)

**Comment by fdschmidt93** [comment]
I'll quadruple check this throughout the day because there's quite some scenarios now to cover. Maybe I'll look into how to write appropriate tests for this, though I think if this now works we should be good apart from a person remapping `<ESC>` :laughing:

**Comment by Conni2461** [comment]
Thats a lot. I think it looks good. The only thing that is still bothering me is the fact that we `vim.schedule` every time. I think we only need to do that if we go from picker to picker. Of the top of my head, i dont have a good idea how to determine that. But no vim.schedule should fix #1898 and ( #1911 ) (even thought that doesnt matter, would still be a good test case).

We could do a new PR, thought to figure out that `vim.schedule` stuff

**Comment by fdschmidt93** [comment]
Yeah, let's merge this.

I've attempted writing tests for this but I think the tests always pass before the `assert` gets actually triggered :sweat_smile: 

Let's do these things in a follow-up PR.

**Comment by Conni2461** [comment]
> I've attempted writing tests for this but I think the tests always pass before the assert gets actually triggered

Tj also rewrote "test framework" in fps :laughing:

**Pull request merged**
