### PR TITLE
add Normal highlights for prompt and results

### PR DESCRIPTION
**Pull request by max397574**
@l-kershaw

### CODE REVIEW

**Comment by max397574** [comment]
Screenshot 2021-11-29 at 14 30 49


this pr allows custom highlight groups for prompt and results

**Comment by l-kershaw** [comment]
This works well for me; the only thing I would change right now is remove the comment in this line:
https://github.com/nvim-telescope/telescope.nvim/pull/1514/files#diff-afd2d88a2ed63b01b66015f5836a104ce81a8f6daac1b6f70692e1f4534b5f0bL19
as it (and the blank line above it) is no longer needed.

---

I also want to double check with another team member why `TelescopePreviewNormal` is linked to `Normal` rather than `TelescopeNormal`, and whether we should change it so everything matches. @Conni2461 you merged this in #460, was there a particular reason for this? Should we change it so the behaviour is consistent for all window types?

**Comment by Conni2461** [comment]
No reason. It just happened because i didnt pay enough attention.

**Comment by max397574** [comment]
idk if we could also try to fix this here @l-kershaw 
https://github.com/nvim-telescope/telescope.nvim/issues/1507#issuecomment-981467737

**Comment by l-kershaw** [comment]
@Conni2461 thanks for the quick response 😊
I know you're trying to keep telescope work to the weekend, so I do appreciate it.
I don't think it was an attention thing, it just didn't make any difference at the time, since "preview" was the only part that was separated out 🙂

---

@max397574 I can't reproduce the issue from the comment, either on master, or with this PR checked out.
Therefore I think it would be best to open its own issue, and we can handle it separately.

For this PR, I'm happy to merge now, but will wait until you let me know that you are happy with this plan of handling things separately 🙂

**Comment by max397574** [comment]
yes I think it's good as it is now @l-kershaw

**Pull request merged**
