### PR TITLE
feat: goto next/previous entry from last picker

### LINKED ISSUE #1701: Allow users to "resume" last known picker state
**Is your feature request related to a problem? Please describe.**

- I want to find and poke around in all files that include the text "foobar".
- I have `:Telescope list_files` mapped to `<leader>f`.
- I hit `<leader>f` to open the modal and filter the results by entering the text "foobar". 
- I enter the first file to look around.
- I now want to go to the next file. I hit `<leader>f` and have to enter "foobar" again to list the files.

**Describe the solution you'd like**

It would be neat if I could repeatedly hit `<leader>f` and the picker would resume to the last known state.

**Describe alternatives you've considered**

Reddit pointed me towards `:Telescope resume` which, in large, solves my problem. The solution has the following drawbacks:

- `:Telescope resume` requires another keybinding.
- I have `<leader>f` in muscle memory, if I hit it by accident the last known state is reset.
- If I use a different picker in-between navigation between files, the state is reset.

**Additional context**

This feature would probably require a more advanced cache eviction strategy, updated documentation, a carefully thought-out API to reduce unnecessary memory usage etc. I could probably get used to a separate binding to resume the state. But let's discuss!

Reddit discussion here: https://www.reddit.com/r/neovim/comments/s696vk/telescope_fzf_ag_for_live_grep/ht5j6it/

### PR DESCRIPTION
**Pull request by fdschmidt93**
40 mins of a bit of telescope hacking :)

Closes #1701 

Now you can

```lua
local actions = require "telescope.actions"
-- also works for actions.move_selection_previous
local select_next = actions.move_selection_next + actions.select_default
-- .. launch picker
select_next() -- go to next result of last picker
```

e: goes without saying but this is ulow prio :sweat_smile:

### CODE REVIEW

**Comment by wcascades** [comment]
Is there a status update on this? Seems it's been stale for a while.

**Comment by fdschmidt93** [comment]
I'd be very happy for somebody to take this over assuming @Conni2461 signs off on this being a feature we should incorporate into telescope-core.

It's something users requested here and there and but you can also make the argument we are reinventing the quickfix list here.

**Comment by c3n21** [comment]
> I'd be very happy for somebody to take this over assuming @Conni2461 signs off on this being a feature we should incorporate into telescope-core.
> 
> It's something users requested here and there and but you can also make the argument we are reinventing the quickfix list here.
I'd love to help out with this PR which is the very thing that prevents me from fully switching to Telescope even as file browser but I need some clarification.

In short this PR should allow a behavior similar to quickfixlist's **:cnext** and **:cprev** right?
I'm a bit confused because the related issue is about restoring the last known state of the picker invoked, but the PR even though related to that seems to have a slightly different scope, namely only allowing to cycle through the entries of the last known state of the picker.

Also I don't get how to test out this feature.

What I'm doing now is (on your branch and with **minimal_init.vim**):
1. Running Telescope find_files
2. Typing some random stuff and selecting the entry
3. Running the snippet in the PR's description and getting this error:

```
E5113: Error while calling lua chunk: ...acker/start/telescope.nvim/lua/telescope/actions/set.lua:39: attempt to index a nil value
stack traceback:
        ...acker/start/telescope.nvim/lua/telescope/actions/set.lua:39: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'shift_selection'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:81: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'select_next'
        test.lua:13: in main chunk
```

**Comment by arv-sajeev** [comment]
Any update on this PR?

**Comment by fdschmidt93** [comment]
Sorry, as mentioned before I will not be continuing this. Happy for anyone to take over :)

**Pull request closed without merging**
