### PR TITLE
fix: help

### PR DESCRIPTION
**Pull request by Conni2461**
CC @clason 

fixes regression in https://github.com/nvim-telescope/telescope.nvim/pull/2551

currently anon functions aren't figured out like before

### CODE REVIEW

**Comment by Conni2461** [comment]
problem is with functions that aren't telescope actions we need to open the source file and check the content.

But with the new implementation we need to figure out the desc on mapping register, not sure if its worth to do that

**Comment by Conni2461** [comment]
but it might actually be just a handful of cases so it might not even have an impact

**Comment by Conni2461** [comment]
got a better idea, we could just serialize the `debug.getinfo` into the desc so we can still "scrape" the information on action open

**Comment by Conni2461** [comment]
okay, think i got it back to the previous functionality. @clason do you have a sec and could test it

**Comment by Conni2461** [comment]
nah i think we should keep it, even though i dont use it, it helps new users to get going, so it has a purpose.

The new hack isn't that bad ^^ and its only used to store information about anonymous functions which isn't that common anyway

**Comment by clason** [comment]
And it works nicely :)

**Comment by Conni2461** [comment]
thx for testing :)

**Pull request merged**
