### PR TITLE
Revert "fix: Better highlights"

### PR DESCRIPTION
**Pull request by sunjon**
Reverts nvim-telescope/telescope.nvim#344

### CODE REVIEW

**Comment by tami5** [comment]
@sunjon did you merge 344 by mistake ?

**Comment by Conni2461** [comment]
sunjon broke almost everything 😆

**Comment by sunjon** [comment]
I'd been testing it throughout the day, and not managed to find the errors that @Conni2461 and @clason found in minutes.
+1 for me/us mastering integration tests. Sorry!

**Comment by tami5** [comment]
:smile: @Conni2461 . I think there iss an issue closed that need to be reopen

**Comment by tami5** [comment]
@sunjon its alright things like this happen all the time

**Pull request merged**
