### PR TITLE
fix: stale lnum in buffer previewer

### LINKED ISSUE #1226: Cursor position outside buffer error when opening from buffer picker and cursor is on the first column
### Description

When opening a buffer in a new tab from the buffer picker using `<c-t>` it seems that if the cursor is on the first column of the line the set cursor command at line 741 of the internal.lua file fails. I can successfully reproduce it inside log buffers, but it's a bit sporadic in other situations.

This relates to #957 which showed a similar error with an associated PR which fixed I think a part of this issue but there could also be another instance of the same bug in the related file below. 
```
E5108: Error executing lua ...er/opt/telescope.nvim/lua/telescope/builtin/internal.lua:741: Cursor position outside buffer
```
cc @Conni2461 (raised it as a separate issue as mentioned in the linked issue)

### Neovim version

:version
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmis
sing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FR
OM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacO
SX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info

### Operating system and version

macOS Big Sur & Ubuntu 20.04

### Steps to reproduce

1. Set buffer picker config to (Optional, maybe)
```lua
      buffers = {
        sort_mru = true,
        sort_lastused = true,
        show_all_buffers = true,
        ignore_current_buffer = true,
        previewer = false,
        theme = 'dropdown',
        mappings = {
          i = { ['<c-x>'] = 'delete_buffer' },
          n = { ['<c-x>'] = 'delete_buffer' },
        },
      },
```
2. open a file and move the cursor to the start of a line
3. move to another file
4. try to open the original file in a new tab using `<c-t>`

### Expected behavior

Should not error

### Actual behavior

Throws the above error

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by fdschmidt93**
Closes #1226 

@Akinsho does this also work for you? Your hunch is correct and I can reproduce this when resuming a buffer previewer to jump to a buffer for which the lnum for the respective buffer became stale in the mean time (eg from deleting bottom).

Not 100% sure about your tabpage log buffer scenario though :sweat_smile: I've tried to keep it simple and practical.

### CODE REVIEW

**Comment by fdschmidt93** [comment]
Apologies @akinsho -- the thumbs up is confirmation that this works for you just as well? Then I'd ride this another ~15 minutes with every conceivable use case I can think of and merge this, as the changes are (fingers crossed) otherwise quite innocent.

**Comment by akinsho** [comment]
@fdschmidt93 ah sorry for the ambiguous response was in a rush at the time, was mainly just acknowledging the PR awesome you found a fix will test it out now and let you know

**Comment by akinsho** [comment]
@fdschmidt93 turns out I won't be able to have a look myself till tomorrow, feel free to merge without me and I'll re-test in the morning otherwise happy to give the branch a go then.

**Comment by akinsho** [comment]
@fdschmidt93 finally managed to test things out today and haven't seen a recurrence of the issue 👍🏿 , thanks for the fix 😄

**Comment by fdschmidt93** [comment]
Thanks a lot for test driving this :) I've also gave this another whirl. Should be fine.

**Pull request merged**
