### PR TITLE
add "append" mode to previewers.utils.job_maker

### PR DESCRIPTION
**Pull request by pwntester**

### CODE REVIEW

**Review by Conni2461 — APPROVED** [review]
LGTM but now I have the feeling that we are losing control of the parameters. 🤣

But tbh i also don't really mind.

**Comment by Conni2461** [comment]
Talked with @tami5. Lets make a table and have the table as last parameter. That means you also have to update 4 builtin previewer. Sorry about that :)
We can add:
```lua
{
  env,
  value, -- value can be optional because its only here for the cache
  mode,
  callback
}
```

**Comment by pwntester** [comment]
> LGTM but now I have the feeling that we are losing control of the parameters. 🤣

Yep, maybe it should be better to make it an `opts` dict.

**Comment by pwntester** [comment]
> ```lua
> value can be optional because its only here for the cache
> ```

so is `bufname`, should I make it also part of the dict and optional?

**Comment by Conni2461** [comment]
Yes thanks :). Forgot about that 😆

**Review by Conni2461 — APPROVED** [review]
Thats much better. Thanks :)

**Comment by tami5** [comment]
LGTM thanks @pwntester

**Pull request merged**
