### PR TITLE
WIP fix escapeing windows special chars

### LINKED ISSUE #2446: Telescope unable to preview and open files with sveltekit advanced layouts
### Description

When using telescope search files or live grep within a sveltekit project telescope is unable to preview or open files contained within a sveltekit advanced layout group: [sveltekit docs](https://kit.svelte.dev/docs/advanced-routing).

### Neovim version

```markdown
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az28-353
```

### Operating system and version

Windows 11

### Telescope version / branch / rev

telescope 0.1.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.7.0

## ===== Installed extensions =====
```

### Steps to reproduce

Within a sveltekit project using the advanced routeing -> advanced layout -> (groups).
Open a search files or live grep telescope window and search for content that will be nested below the route like /routes/(group)/.
The preview window will not display any content.
Then use your bound key or <CR> to open the selected file.
The route will show as /routes(group)/ with the / preceding the group not displaying.
This will open a new buffer with no content.

### Expected behavior

That telescope is able to parse, display preview, and open files contained within these routes.

### Actual behavior

Telescope is unable to preview content and open files contained within these routes

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by davisthedev**
# Description

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context

Fixes #2446 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list relevant details about your configuration

- [x] Tested on windows by navigating Telescope pickers and opening files to ensure special characters were escaped.

**Configuration**:
* Neovim version (nvim --version): 0.9.1
* Operating system and version: Windows 11

# Checklist:

- [x] My code follows the style guidelines of this project (stylua)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (lua annotations)

### CODE REVIEW

**Comment by jamestrew** [comment]
@Conni2461 I'm thinking some of this probably belongs in plenary.path.

@davisthedev I'm also curious if using `:set shellslash` helps in any way in telescope.

**Comment by davisthedev** [comment]
@jamestrew I did try :set shellslash before I started any dev work. It did not make a difference for telescope.

I would be happy to add this to plenary if that would help? 
I am super new to lua and the neovim ecosystem so I may have some questions.

**Comment by jamestrew** [comment]
Semi-related issue with plenary not gracefully handling windows paths set `shellslash` https://github.com/nvim-telescope/telescope.nvim/issues/2651

**Comment by Conni2461** [comment]
i think we should do that in plenary. And we already had a discussion about this in plenary

https://github.com/nvim-lua/plenary.nvim/issues/254
https://github.com/nvim-lua/plenary.nvim/pull/371

**Pull request closed without merging**
