### PR TITLE
feat: add no_ignore option to find_files

### PR DESCRIPTION
**Pull request by lmarlow**
This will allow find_files to find files ignored by .gitignore
and other ignore files. This is supported by fd, rg, and fdfind.

### CODE REVIEW

**Comment by tami5** [comment]
LGTM, but what id the user would like to keep git ignore hidden but want dotfiles to be included ?

**Comment by lmarlow** [comment]
> LGTM, but what id the user would like to keep git ignore hidden but want dotfiles to be included ?

@tami5, the `hidden` option will show dotfiles. The `no_ignore` option will show files normally hidden by patterns in `.gitignore`.

**Comment by tami5** [comment]
Nice, thanks @lmarlow

**Comment by nachiket87** [comment]
omg thank you! @lmarlow

**Pull request merged**
