### PR TITLE
Mirror option for bottom_pane layout_strategy

### PR DESCRIPTION
**Pull request by smithbm2316**
I'm not crazy about the naming I chose, but it's late and I'm tired and I got it to at least by functional to how I liked it :slightly_smiling_face:. Adds a `mirror` option (similar to how `mirror` works for the `flex`, `horizontal`, and `vertical` layouts) for @tjdevries' latest layout_strategy concoction `bottom_pane`. I'm weird and I like my results and preview windows flipped the opposite way of apparently everyone else who uses Telescope :rofl: 

Edit: idk why I marked it as WIP, it does work well afaik. I just as mentioned before don't love the naming I chose and probably want to refactor that when my brain is not very tired lol

### CODE REVIEW

**Comment by tami5** [comment]
LGTM, maybe we should merge if there isn't anything left todo.

Also, well done, 😂 there are many things I want to do with layout but failed to do so😪.

**Comment by smithbm2316** [comment]
> LGTM, maybe we should merge if there isn't anything left todo.

@tami5 I think I want to rename `left_side_width` to something else maybe, as that may not be the most intuitive name. 

Also, I think we may want to wait for #823 to be merged so we have the big incoming changes to `layout_config` and `layout_defaults` finished first. 

> Also, well done, 😂 there are many things I want to do with layout but failed to do so😪.

Thank you lol TJ did all the hard work, I just tweaked it a bit.

**Comment by tjdevries** [comment]
I can just incorporate these changes in for you in the other pr.

**Comment by smithbm2316** [comment]
> I can just incorporate these changes in for you in the other pr. 

That works for me! Thanks TJ :)

**Comment by Conni2461** [comment]
Btw tj did not integrate that in his PR, what a shame :rofl: So you should probably rebase and then we merge this PR :)

CC @smithbm2316

**Comment by smithbm2316** [comment]
> Btw tj did not integrate that in his PR, what a shame rofl So you should probably rebase and then we merge this PR :)
> 
> CC @smithbm2316

I'll take a look at fixing and merging this in the coming day or two

**Comment by smithbm2316** [comment]
@Conni2461 sorry for my apparent inability to read a git diff :man_facepalming: #1022 should have fixed the small bug I introduced with this PR. The mirror option for the `bottom_pane` layout should be working now in master!

**Comment by Conni2461** [comment]
Next time, let someone review it :) i think we can always wait a little bit, we never need to rush time :laughing:

**Pull request merged**
