### PR TITLE
fix: wrong win on selection

### LINKED ISSUE #1949: Open files on the first window only
### Description

On git_files (not tested with other pickers) the selected file is opening only on the first window opened in neovim.

The line that triggered this big is probably `lua/telescope/actions/set.lua:134`, after reverting it on my computer the expected behaviour was back.

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -I/opt/homebrew/opt/llvm/include -I/opt/X11/include -I/opt/local/include -U_
FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-
parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissin
g-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIO
NS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/emilienlemaire/Development/c/neovim/build/config -I/U
sers/emilienlemaire/Development/c/neovim/src -I/Users/emilienlemaire/Development/c/neovim/.deps/usr/include -I/opt/local/include -I/User
s/emilienlemaire/Development/c/neovim/build/src/nvim/auto -I/Users/emilienlemaire/Development/c/neovim/build/include
Compiled by emilienlemaire@Emiliens-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

### Operating system and version

macOS 12.3

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `toggleterm`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Update telescope to commit b4c45e8
2. Open several windows in vim
3. Place yourself in any window but the first one
4. `:Telescope git_files()` (might be the same with other commands I did not tested other commands yet)
5. Select a file you want to open

### Expected behavior

Open the file in window the cursor was in

### Actual behavior

Open the file in the first window that was opened by vim.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by fdschmidt93**
Fix regression from #1202 

Closes #1949 #1950

I like to think that this is the most elegant way to go about it :sweat_smile: but maybe I'm missing something

@emilienlemaire @ribelo could you please confirm that this fix works for you and maybe test quickly whether no regression in your typical workflow is visible?

### CODE REVIEW

**Comment by emilienlemaire** [comment]
The fix works well on my config, no regression found in typical workflow 😄

**Comment by Conni2461** [comment]
Uff one sec

**Comment by Conni2461** [comment]
We need to set the original win id before `normal! m'` and pushing tagstack. After that we need to be able to set a custom win id. So actually i would just do this diff

```lua
require("telescope.pickers").on_close_prompt(prompt_bufnr)
pcall(vim.api.nvim_set_current_win, original_win_id)

-- push_cursor
-- push tagstack
-- potentially set new win
```

**Comment by fdschmidt93** [comment]
Ah, makes sense yes. Done.

**Review by Conni2461 — APPROVED** [review]

**Comment by fdschmidt93** [comment]
MacOS test failures are unrelated (can't pull nightly). I'll merge as this is a critical bug that requires an ad-hoc fix.

**Comment by Conni2461** [comment]
thanks :)

**Pull request merged**
