### PR TITLE
feat: add optional plugin picker

### PR DESCRIPTION
**Pull request by kuntau**
Make it easier to load optional plugin (`packadd`)

### CODE REVIEW

**Comment by kuntau** [comment]
Uff.. first timer here.

> Auto-updates from CI

I need help with this

**Comment by Conni2461** [comment]
We are currently not looking for new builtins

**Comment by kuntau** [comment]
> We are currently not looking for new builtins

May I know why? This is just a simple vim command that I use all the time. It's much more convenient to have picker for them.

**Comment by fdschmidt93** [comment]
As to why, much of is discussed here: https://github.com/nvim-telescope/telescope.nvim/issues/1228

**Comment by kuntau** [comment]
> You could just create an extension for this I think

Sure, but it's just too small in functionality and code to be worth as extension IMO

**Comment by max397574** [comment]
Then it would be a small extension ig

**Comment by Conni2461** [comment]
I am sorry but i have to deny this PR. You should put this picker in your local config if it benefits you or create a small extension.

Still thanks for the PR :) and i am very sorry.

**Pull request closed without merging**
