### PR TITLE
feat: smart path

### PR DESCRIPTION
**Pull request by qualious**
Hey! 

I had some spare time this evening and wanted to implement this feature that we previously discussed with @Conni2461. 

This was proposed before and was discussed [here](https://github.com/caojoshua/telescope.nvim/pull/1)

To give a brief description:

given files

```
a/b/c/d/e/f
a/b/c/q/h/u
a/b/c/d/e/h

```

"smart" path shows 

```
../d/e/f
../q/h/u
../d/e/h
```

Screenshot 2021-06-17 at 14 51 13

---

To further illustrate:

Screenshot 2021-06-15 at 01 17 46

when

```
src/app/components/Header/index.tsx
src/app/components/InfoTable/styled.ts
```
--- 

If all resulting search files are the same logic still holds:

Screenshot 2021-06-15 at 11 35 23

---

Let me know what you guys think!

### CODE REVIEW

**Comment by tami5** [comment]
Awesome work, this improves readability by  a lot

**Comment by qualious** [comment]
any updates on this?

**Comment by Conni2461** [comment]
As i said before will happen after https://github.com/nvim-telescope/telescope.nvim/pull/839, he came first ;) I try to review stuff and make it happens this week but i am still pretty busy

**Comment by Conni2461** [comment]
#839 is merged now so i will take another look at your pr after `smart path` is integrated into the new `path_display` "system".

Thanks for your patients :)

**Comment by EpsilonKu** [comment]
Any update?

**Comment by Conni2461** [comment]
Seems that this PR was abandoned i just resolved the conflicts and integrated it in `path_display`. I still need to test it but i plan to merge it today :)

**Comment by tami5** [comment]
> Seems that this PR was abandoned so i finish it. I just resolved the conflicts and integrated it in `path_display`. I still need to test it but i plan to merge it today :) 
> 
> 
> 
> You then can do `path_display = { "smart" }` similar to how you can set `shorten`

❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️ Thanks so much, I was so looking forward to it

**Review by Conni2461 — APPROVED** [review]
I think this is good. Its hard for me to comment on the algorithm without having the original author here to talk to.

So i merge this and if it isnt 100% what people expect than the community can still iterate on it (the core team probably wont iterate on it)

**Pull request merged**
