### PR TITLE
Revert revert revert revert revert revert revert revert revert revert revert revert revert 

### PR DESCRIPTION
**Pull request by tjdevries**

### CODE REVIEW

**Comment by Conni2461** [comment]
Devicons test is still failing for me. Works as expected when using telescope.
```
Fail    ||      builtin.find_files use devicons, if it has it when enabled
            .../plugged/telescope.nvim/lua/telescope/pickers/_tests.lua:113: Expected objects to be the same.
            Passed in:
            (string) '> README.md'
            Expected:
            (string) '>  README.md'

            stack traceback:
                .../plugged/telescope.nvim/lua/telescope/pickers/_tests.lua:113: in function 'check_results'
                .../plugged/telescope.nvim/lua/telescope/pickers/_tests.lua:153: in function 'run_string'
                ...ope.nvim/lua/tests/automated/pickers/find_files_spec.lua:47: in function <...ope.nvim/lua/tests/automated/pickers/find_files_spec.lua:28>
```

**Comment by tjdevries** [comment]
Failed for you locally? And do you have devicons installed?

**Comment by Conni2461** [comment]
Yeah it fails locally and i know why. When adding `set rtp+=../nvim-web-devicons/` to the `minimal_init.vim` it works so i have no idea why it was working for you and CI previously.

**Comment by tjdevries** [comment]
Hmm.... it should skip the test if you don't have devicons. so i'm not sure :laughing:

**Comment by tjdevries** [comment]
Ah, it auto adds it to the rtp because of where we install them. we don't even have to have a minimal init.vim for it I think.

**Comment by Conni2461** [comment]
Yeah for CI we add install them directly to `pack/*/start` so our live is easier. At least that was in my mind when writing it. I just don't get how you have `devicons` inside your nvim process that has only the `min_rc` and that `min_rc` doesn't even source it.

**Pull request merged**
