### PR TITLE
fix: update `multi_icon` with `select/drop/toggle_all` actions

### LINKED ISSUE #1663: `selection_prefix` not redrawn after `actions.toggle_all`
### Description

`selection_prefix` (`+` by default) is redrawn when using actions by default mapped to `<Tab>` and `<S-Tab>`, but not for actions `actions.toggle_all`, `actions.select_all` and `actions.drop_all`.

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

### Operating system and version

macOS 12.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. `:Telescope find_files`
2. `<A-a>`

### Expected behavior

image

### Actual behavior

image

(only highlighting is used for selected items, no selection marker)

### Minimal config

```Lua
return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use { 'nvim-telescope/telescope.nvim',
    requires = 'nvim-lua/plenary.nvim',
    config = function()
      actions = require "telescope.actions"
      require('telescope').setup{
        defaults = { mappings = { i = {
          ["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
          ["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
          ["<A-a>"] = actions.toggle_all
        }}}}
    end
  }
end)
```
```

### PR DESCRIPTION
**Pull request by l-kershaw**
Resolves #1663

@SimonMandlik does this fix your issue?

### CODE REVIEW

**Comment by SimonMandlik** [comment]
I'm getting this error

```
E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1009: attempt to get length of local 'old_caret' (a boolean value)
stack traceback:
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1009: in function 'update_prefix'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:116: in function 'f'
        ...ker/start/telescope.nvim/lua/telescope/actions/utils.lua:45: in function 'map_entries'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:112: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:236: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

when invoking any of the multi-select actions.

Not sure how to properly install you fix, did it in packer with

```
    use { 'l-kershaw/telescope.nvim',
        branch = 'fix/multi_icon_select_all',
        requires = { 'nvim-lua/plenary.nvim',
            { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' }
        },
        config = function() require('config.telescope') end
    }
```

**Comment by l-kershaw** [comment]
@SimonMandlik I've added a check for old caret being found, and some logging.
Could you try again and let me know what the log messages say for you, and what your values for `selection_caret`, `multi_icon` and `entry_prefix` are?

**Comment by SimonMandlik** [comment]
I've tried it on a small repo and looks to be working, thanks!

However, when I run it in `~` another error appears:

```
E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1002: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
        [C]: in function 'sub'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1002: in function 'update_prefix'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:116: in function 'f'
        ...ker/start/telescope.nvim/lua/telescope/actions/utils.lua:45: in function 'map_entries'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:112: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:236: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

I will gladly provide more details, but I do not know how to display the whole error here

**Comment by l-kershaw** [comment]
@SimonMandlik I'm not sure how that error could ever occur, but have added a logging step to hopefully catch it

Could you let me know what is in the log when you type `:messages` after using these actions? Also what are the values of `defaults.selection_caret`, `defaults.entry_prefix` and `defaults.multi_icon` in your telescope config?

**Comment by SimonMandlik** [comment]
```
[telescope] [WARN  00:48:31] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1012: can't identify old caret in line:
[telescope] [WARN  00:48:31] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1003: no line found at row 1999 in buffer 3
```

The first line is repeated many times, the other is shown only once.

Here's my complete config

```lua
require('telescope').load_extension('fzf')

require('telescope').setup{
    defaults = {
        layout_strategy = 'flex',
        layout_config = {  height = 0.9, width = 0.95, prompt_position = "top" },
        sorting_strategy = 'ascending',            -- default is 'descending'
        multi_icon = "• ",
        mappings = TELESCOPE_MAPPINGS,
        prompt_prefix = "❯ ",
        selection_caret = "  "
    },
    pickers = {
        find_files = {
            -- show hidden files
            hidden = true,
            -- follow symlinks
            follow = true,
            -- show files in .gitignore
            no_ignore = true,
            -- truncate path if too long
            path_display = { truncate = 1 },
        },
        live_grep = {
            -- do not indent results
            additional_args = function() return { '--trim' } end,
            -- do not show line + columns in results
            disable_coordinates = true,
            -- shorten path
            path_display = { 'shorten' },
        }
    },
    extensions = {
        fzf = {
            case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
        }
    }
}
```

**Comment by l-kershaw** [comment]
@SimonMandlik does this fix things for you?

**Comment by SimonMandlik** [comment]
No errors anymore, just one warning :)

```
[telescope] [WARN  22:34:52] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1012: can't identify
old caret in line:
```

**Comment by l-kershaw** [comment]
I'm hoping this was an off by one error with the inequality and should now be fixed?

**Comment by SimonMandlik** [comment]
Yes, no errors nor warnings now :)

**Comment by l-kershaw** [comment]
@SimonMandlik I've merged in the latest master, and added updates for the new multi-selection count in prompt (introduced in #1614). Could you check that everything still works for you and that the count updates as you would expect with the `select/drop/toggle_all` actions?

**Comment by SimonMandlik** [comment]
Everything still works :)

**Comment by l-kershaw** [comment]
Great, thanks 🙂

Merging now

**Pull request merged**
