### PR TITLE
Full width select

### PR DESCRIPTION
**Pull request by TC72**
New PR.

### CODE REVIEW

**Comment by fdschmidt93** [comment]
Thanks taking another crack at this :)

I think what Conni meant with version bump entails:
* grep for 'nvim-0.5' and replace `has("nvim-0.5")` with `has("nvim-0.5.1")`, essentially. Mentioning it like that since, I think quotation marks are a bit inconsistent between `.vim` and `.lua`
* updating https://github.com/nvim-telescope/telescope.nvim#getting-started

**Comment by Conni2461** [comment]
We can also do 1 PR with 2 commits and we dont squash

**Comment by fdschmidt93** [comment]
Ah yes, simple solutions :laughing: :sweat_smile:

**Comment by TC72** [comment]
Do I need to do another commit where I explicitly say "Update plugin requirement to nvim 0.5.1"?

I'll understand how I'm supposed to do this one day.

**Comment by fdschmidt93** [comment]
> Also from Conni's note, should I have done a commit where I explicitly say "Update plugin requirement to nvim 0.5.1"?

Yes, two commits (ideally not but not necessarily in order):
1. BREAKING: bump minimum nvim version to 0.5.1 (then e.g. Packer highlights these)
2. feat: full-width hl of selection

I realize that requires a bit of git-gymnastics; that's why I thought it's just suggested to bump in a separate PR.

Not sure, but we might want to have a sticky issue with breaking changes as well.

**Comment by TC72** [comment]
OK, I removed the version bump from this PR and crated this one: #1405

**Comment by Conni2461** [comment]
Thanks :)

FWIW the "git-gymnastics" should have been the easier route. Less branch switching, etc. :laughing:

**Pull request merged**
