### PR TITLE
fix: show error message when nothing is selected

### PR DESCRIPTION
**Pull request by jonasstr**
This continues the fixes done in 4816a27d7680feed293d21a945c476947af20d29 (ref #1283).

The only picker that shows this error now (of those I tested) is `Telescope buffers` - I did not fix this one because there is already a message saying "[telescope] Nothing currently selected" above the nil error message (not sure why it's shown twice).

### CODE REVIEW

**Comment by l-kershaw** [comment]
Thanks for the PR!

There are a few cases where the relevant variable is called `entry` rather than `selection`, which means that `selection` is not defined. This is what is causing the `luacheck` to fail.
In these cases, I would suggest you rename the `entry` variable to `selection` as it is a bit clearer about what the variable represents (make sure you change all of the references to `entry` to `selection`, e.g. `entry.value` -> `selection.value`).

Also, I think it would be better to use `telescope`'s logging system rather than just a `print` to inform the user that nothing is selected. Maybe use `log.warn`?

Feel free to ping me if you have any questions 🙂

**Comment by jonasstr** [comment]
Yeah sorry I am not sure why I forgot to change this! :) Ok I will look into `log.warn`. Should I just add more commits here (I assume they will be squashed when merging) or force-push to the existing branch? Thanks :smile:

**Comment by l-kershaw** [comment]
Just adding more commits is fine (I normally end up with a load of extra ones trying to keep the linting happy 😅).
We always squash when merging, so its better to keep the commit history in the PR (where possible), in case we need to go back and look at it 🙂

**Comment by Conni2461** [comment]
Just saying i dont think we need `log.*` here, we can just `print` because there is no real reason to write it in the log file. Also i decided for `print` yesterday because we already have that exact same "code block" in actions.set with a print

https://github.com/nvim-telescope/telescope.nvim/blob/a6c7498bdcd661e86ec0c1181ed50024beb540f7/lua/telescope/actions/set.lua#L90-L93

**Comment by l-kershaw** [comment]
> Just saying i dont think we need log.* here, we can just print because there is no real reason to write it in the log file. Also i decided for print yesterday because we already have that exact same "code block" in actions.set with a print

Fair enough. It shouldn't make much of a difference either way, so happy to leave it as `print` 👍

**Comment by jonasstr** [comment]
> Just adding more commits is fine (I normally end up with a load of extra ones trying to keep the linting happy).

Well, I'm glad I'm not the only one :sweat_smile:. Sorry for the extra commits..

**Comment by l-kershaw** [comment]
LGTM, thanks for the PR  👍

No worries about the extra commits 🙂

**Pull request merged**
