### PR TITLE
fix(previewer): ft detect for filetypes defined as functions

### PR DESCRIPTION
**Pull request by Conni2461**
still need to resolve binary warning

CC @clason

### CODE REVIEW

**Comment by clason** [comment]
> still need to resolve binary warning

probably due to the timeout?

otherwise it seems to work fine

**Comment by Conni2461** [comment]
binary should also be fixed

**Comment by clason** [comment]
yep, everything seems to work now, thanks for the quick fix!

**Comment by Conni2461** [comment]
thanks for testing and reporting. i gonna open an issue on neovim, for that problem i found later today :)

**Comment by clason** [comment]
Yes, the combination `filename` + `contents` is not supported (yet). It's a reasonable feature request, though. (Not a bug, since that combination is not documented to work.)

**Comment by Conni2461** [comment]
> Not a bug, since that combination is not documented to work

ah good point, yeah then there is no rush ^^

**Comment by clason** [comment]
But the reason it's not implemented is that nobody has asked for it yet ;)

**Pull request merged**
