### PR TITLE
buffer_dir returns an expression to be expanded

### LINKED ISSUE #1440: `Telescope.file_browser` does not honour the `cwd = require("telescope.utils").buffer_dir()`
### Description

`Telescope.file_browser` does not honour the `cwd = require("telescope.utils").buffer_dir()` configuration. It works at the first time when opening the file/buffer from terminal and then ignore whatever buffer's location you are working on.

A solution perhaps would be a callback: `cwd = require("telescope.utils").buffer_dir`?

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/config -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/src -I/opt/homebrew/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/include
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info

### Operating system and version

macOS 12.0.1

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 
 
## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1
 
## ===== Installed extensions =====
 
## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `touch file0`
2. `mkdir dir`
3. `touch dir/file1`
4. `touch dir/file2`
5. `nvim -nu minimal.lua file0`
6. `:Telescope file_browser`
7. It correctly lists the directory pertaining to `file0`.
8. Open `dir/file1` (via file_browser)
9. `:Telescope file_browser`
10. It **INCORRECTLY** lists the directory pertaining to `file0`, instead of the one belonging to `dir/file1`.

### Expected behavior

To honour the `cwd = require("telescope.utils").buffer_dir()` configuration.

### Actual behavior

It will open the initial buffer_dir() from `file0`, instead of the current buffer's folder.

https://asciinema.org/a/1TiGHzCxydN1ia38iBJP8I9gG

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-telescope/telescope.nvim",
				requires = {
					"nvim-lua/plenary.nvim",
					{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
				},
			},
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	require("telescope").setup({
		pickers = {
			file_browser = require("telescope.themes").get_dropdown({
				cwd = require("telescope.utils").buffer_dir(),
				previewer = false,
			}),
		},
	})
	require("telescope").load_extension("fzf")
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing Telescope and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

### PR DESCRIPTION
**Pull request by horta**
Closes #1440

### CODE REVIEW

**Comment by fdschmidt93** [comment]
Thanks for your PR :) however, users might already rely on the function like that and what we maybe should do instead is clarifying that `opts.cwd` for `builtin.{find_files, live_grep, file_browser, ..}` accepts strings that can be expanded with `vim.fn.expand` (like the one in `require "telescope.utils".buffer_dir`). In any case, `require "telescope.utils".buffer_dir` seems a bit redundant to me, though I guess it's a convenience for users.

To that end, we would have to improve the docs at

https://github.com/nvim-telescope/telescope.nvim/blob/f3ef5920725d719ed23195a457a86015826d3e1d/lua/telescope/builtin/init.lua#L56

https://github.com/nvim-telescope/telescope.nvim/blob/f3ef5920725d719ed23195a457a86015826d3e1d/lua/telescope/builtin/init.lua#L66

https://github.com/nvim-telescope/telescope.nvim/blob/f3ef5920725d719ed23195a457a86015826d3e1d/lua/telescope/builtin/init.lua#L78

https://github.com/nvim-telescope/telescope.nvim/blob/f3ef5920725d719ed23195a457a86015826d3e1d/lua/telescope/builtin/init.lua#L98

https://github.com/nvim-telescope/telescope.nvim/blob/f3ef5920725d719ed23195a457a86015826d3e1d/lua/telescope/builtin/init.lua#L120

Hopefully I've caught all that are relevant.

Thoughts?

**Comment by horta** [comment]
I agree with you. I like the idea of having the documentation changed as to:

```
---@field cwd string: root dir to browse from (default: cwd, use "%:p:h" to search relative to open buffer) 
```

This way the function utils.buffer_dir() can live and we fix a bug (IMHO) in the documentation.

**Comment by fdschmidt93** [comment]
What I find missing is a description of the underlying mechanism. What about 

`---@field cwd string: root dir (default: cwd, levers |expand| to e.g. search relative to open buffer with "%:p:h")` 

which I think makes clearer how it works, (should) link to `expand`, and thereby indicates what else is possible.

**Comment by Conni2461** [comment]
Closing because its stale and I never liked the util function because its unnecessary and merging this change doesnt make it better .

If someone else wants to improve the docs, please open a new pr

**Pull request closed without merging**
