### PR TITLE
Add hidden to find_files file findin'.

### PR DESCRIPTION
**Pull request by Julian**
(Allows including hidden files in file findin'.)

### CODE REVIEW

**Review by Conni2461 — APPROVED** [review]
LGTM. Thanks :)
I will test it later and then merge

**Comment by Conni2461** [comment]
Oh sry. I forgot about this one and now there is a conflict :). Could you please rebase the PR after that i will merge

**Comment by Julian** [comment]
Done.

**Comment by Conni2461** [comment]
Thanks :)
CI is currently not working because neovim nightly build vanished from github. 😆

**Pull request merged**
