### PR TITLE
breaking: bump nvim version requirement to 0.5.1

### PR DESCRIPTION
**Pull request by TC72**
Neovim 0.5.1 is required for #1403 or it will cause a segfault.

### CODE REVIEW

**Comment by fdschmidt93** [comment]
As to your question earlier, I briefly checked, you can replace `0.5.0` with `0.5.1` and then it should work (dl works in browser). Then I think we have it :)

https://github.com/nvim-telescope/telescope.nvim/blob/587a10d1494d8ffa1229246228f0655db2f0a48a/.github/workflows/ci.yml#L12-L28

**Comment by TC72** [comment]
I tried but maybe I don't have permission to change a workflow?
```
! [remote rejected] version_bump_0.5.1 -> version_bump_0.5.1 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
```

**Comment by TC72** [comment]
Had to jump through one extra hoop as my github token wasn't set-up for workflows.
Looks like it's working now.

**Review by fdschmidt93 — APPROVED** [review]
LGTM thanks :) I'd want to have Conni's sign-off though here as well.

**Review by Conni2461 — APPROVED** [review]
LGTM thanks :)

**Pull request merged**
