### PR TITLE
fix(lsp): pass server resp through client handlers (1)

### PR DESCRIPTION
**Pull request by jamestrew**
For LSP methods/pickers:
- references
- definition
- typeDefinition
- implementation

Passes the server results through client (and neovim's) lsp handler function.
This lets those handlers deal with some of the language server specific idiosyncrasies.

Also refactors shared code between these pickers.

Other pickers/methods will need similar treatment.

### CODE REVIEW

**Comment by solson** [comment]
Thanks for the quick PR! When I re-try my reproduction steps from https://github.com/nvim-telescope/telescope.nvim/issues/2768, I run into this error:

```
Error executing vim.schedule lua callback: ...ker/start/telescope.nvim/lua/telescope/builtin/__lsp.lua:147: attempt to index local 'location' (a nil value)
stack traceback:
        ...ker/start/telescope.nvim/lua/telescope/builtin/__lsp.lua:147: in function 'handler'
        ...eovim-unwrapped-0.9.4/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Which suggests that `local location = items[1].user_data` was nil.

**Comment by jamestrew** [comment]
Ah.. it's probably a neovim version issue.
It looks like I'm relying on some bleeding edge changes on nightly (https://github.com/neovim/neovim/pull/25830)

I think we're planning to bump the minimum neovim version requirement to 0.10 for telescope v0.2.0 but there's no timeline for that. Either we come up with a different approach or can't merge this until then.

I'm not sure if I'm in love with my solution anyways. This relies on the custom handlers eventually calling neovim's builtin handler or supporting a `on_list` option like the builtin one does. And I don't think this is a requirement for lsp handlers.

**Comment by josephcrawfordSRH** [comment]
@jamestrew any thoughts on when this may get released?  This fixes an issue I have been having where I cannot jump to the definition for typescript dependencies which are imported via a URL.

**Comment by jamestrew** [comment]
See https://github.com/nvim-telescope/telescope.nvim/issues/2768#issuecomment-2375607071

telescope doesn't handle custom handlers and I don't see any great way of doing so as the linked comment explains.

I'm still thinking about this problem but I don't think this PR is the right approach now.

**Comment by josephcrawfordSRH** [comment]
@jamestrew is there a way to make telescope not handle these, I am not quite sure why gd to jump to a definition would go through telescope at all, I can see gr (references) but not jump to definition.

**Comment by jamestrew** [comment]
That would be dependent on your neovim config. Somewhere you must have gd mapping to telescope.

**Comment by josephcrawfordSRH** [comment]
yep you are correct, it seems LazyVim is doing this by default

https://github.com/LazyVim/LazyVim/blob/13a4a84e3485a36e64055365665a45dc82b6bf71/lua/lazyvim/plugins/extras/editor/telescope.lua#L278-L293

**Pull request closed without merging**
