### PR TITLE
fix: return extension exports on load

### LINKED ISSUE #1632: Frecency and Neoclip broke with commit 3dafcb4
### Description

Commit `3dafcb4` yesterday stopped all the “third-party” telescope extensions from running. 

Eg `:Telescope frecency` returns nothing. 

Reverting to the previous commit lets them run again. 

### Neovim version

```markdown
Nightly
```

### Operating system and version

Debian

### checkhealth telescope

```markdown
No problems found.
```

### Steps to reproduce

Can reproduce with just telescope, plenary and frecency loaded. 

### Expected behavior

_No response_

### Actual behavior

Commit `3dafcb4` yesterday stopped all the “third-party” telescope extensions from running. 

Eg `:Telescope frecency` returns nothing. 

Reverting to the previous commit lets them run again. 

### Minimal config

```Lua
minimal.lua
```

### LINKED ISSUE #1633: Opening a floating window with a new buffer closes telescope
### Description

Opening a floating window that contains a buffer created using `nvim_create_buf` will close the telescope window. It seems to be because a `BufLeave` event is triggered when the window is opened which triggers this https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/pickers.lua#L497. I'm not really sure if this is a bug in neovim or is intended behaviour. This behaviour doesn't occur when a buffer created with `bufadd/bufload` is opened in the window.

Flagged in https://github.com/rcarriga/nvim-notify/issues/46

### Neovim version

```markdown
NVIM v0.7.0-dev+725-g439336079
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/config -I/var/cache/aura/vcs/neovim-git/neovim-git/src/neovim-git/src -I/usr/include -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/src/nvim/auto -I/var/cache/aura/vcs/neovim-git/neovim-git/src/build/include
Compiled by ronan@XPS15

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Arch Linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

```lua
local buf = vim.api.nvim_create_buf(false, true)

vim.cmd([[Telescope find_files]])

vim.loop.new_timer():start(1000, 0, function()
  vim.schedule(function()
    vim.api.nvim_open_win(buf, false, {
      row = 1,
      col = 1,
      width = 1,
      height = 1,
      relative = "editor",
      border = "single",
      style = "minimal",
    })
  end)
end)
```

### Expected behavior

Telescope windows stay open

### Actual behavior

Windows close when new window is created.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

### PR DESCRIPTION
**Pull request by fdschmidt93**
Closes #1632 

Apologies for trouble caused. Could please anyone confirm that it fixes the associated issue?

cc @clason @yigothu @GreatestOfAllTimee @ikerurda @queensferryme

### CODE REVIEW

**Comment by clason** [comment]
It does, as long as you explicitly load the extension (which is a bit of a regression but an acceptable trade-off).

**Comment by fdschmidt93** [comment]
Are you sure? I don't see why that shouldn't work now if it worked before. With this, we essentially invoke extension setup explicitly on `telescope.load_extension`

And I've just checked out the commit before breakage yesterday and `:Telescope frecency` doesn't work for me either without having done `load_extension`.

**Comment by Conni2461** [comment]
I am pretty sure lazyloading doesnt work because we are doing rawget here: https://github.com/nvim-telescope/telescope.nvim/blob/99aa102b384305311308ff573b6790fa53366e10/lua/telescope/command.lua#L183-L185

**Comment by clason** [comment]
Oops, you're right, I hadn't tested with a fresh instance (the commands become available after you execute the (Lua) mapping)!

So, yes, this restores the previous behavior completely.

**Comment by fdschmidt93** [comment]
Ok thanks :) I'll merge this and maybe we can then clean up having to do setup twice with `load_extension` at some other point. It's a minor issue.

**Comment by GreatestOfAllTimee** [comment]
Fixed! Thank you ❤️

**Pull request merged**
