### PR TITLE
Allowed git_files to use vim pwd over git root

### PR DESCRIPTION
**Pull request by tapayne88**
Hi, thanks for the amazing work!

I work in a pretty large git repo and spend my time in a nested folder. What I wanted was an option for `git_files` to only show the git files from my cwd - not the whole project.

I _think_ the only other `git_*` command this might be relevant to is `git_commits` (maybe `git_status`?). I'm not too bothered about those but happy to add it to them.

### CODE REVIEW

**Comment by Conni2461** [comment]
`set_opts_cwd` will apply cwd to all git_* commands. Its a wrapper that runs in front of all commands. Could you check if that is correct? After that we can merge :)

Thanks for the PR
LGTM

**Comment by Conni2461** [comment]
Okay i just tested this. I think we need to add `'--', '.'` to both `git_commits` and `git_status` would be great if you can do that. `dot` should be enough because we already set cwd over our job interface :)

After that i would merge.

Thanks :)

**Comment by tapayne88** [comment]
> `set_opts_cwd` will apply cwd to all git_* commands. Its a wrapper that runs in front of all commands.

Yeah, that's what my testing shows - all `git_*` commands will run through `set_opts_cwd`.

>  I think we need to add `'--', '.'` to both `git_commits` and `git_status`

Yeah I can get that added, from my testing that looks to scope those commands to the `cwd` too 👍

**Comment by Conni2461** [comment]
Could you make CI happy and split up that line :D Similar to how `bcommits` is formatted :)
Thanks after that i press the button

**Review by Conni2461 — APPROVED** [review]
LGTM

Thank you very much :) I know that will make some people happy

**Pull request merged**
