### PR TITLE
feat: quickfix

### PR DESCRIPTION
**Pull request by tjdevries**
I'm working on changing structure of how we store and manage entries.

Once I do that, we can store all the entries.

Once I do that, it should be relatively trivial to turn all the entries into quickfix items.

(still WIP and playing around with new ideas / simple data structures)

### CODE REVIEW

**Comment by elianiva** [comment]
image
image

I got this weird spacing using this branch.

**Comment by tjdevries** [comment]
Ah, I don't know that I've checked descending yet.

**Comment by tjdevries** [comment]
@elianiva is it fixed now?

**Comment by elianiva** [comment]
Yup, it has been fixed.

**Comment by elianiva** [comment]
https://user-images.githubusercontent.com/51877647/103170939-c5ff8780-487a-11eb-91a3-0e79cfed7ea9.mp4

Found another issue. If your cursor is at the bottom of the list and you if you try to go down, it will *broke* the list.
Sometimes the cursor just dissappeared, sometimes the entire list got messed up, and sometimes it jumps to a random position and lost its highlight like I've shown in the vid. Hopefully my video is clear enough.

**Comment by tjdevries** [comment]
I think I fixed your issue, have to fix some testing code though.

**Comment by elianiva** [comment]
can confirm, it works now :)

**Comment by elianiva** [comment]
found an issue with the multiselect highlighting, notice how the highlight didn't get applied when my cursor is placed *below* the selection? It works fine after I move it *above* the selected item.


https://user-images.githubusercontent.com/51877647/104079163-32539100-5254-11eb-84a8-2876f583484c.mp4

**Comment by tami5** [comment]
- `toggle_selection` should select the current line and move to the next line. (kinda expected behavior comming from ranger, although we should have an option to disable it)
- expreinced the same issue from @elianiva report

**Comment by Conni2461** [comment]
1. Do we wanna put `LinkedList.lua` into plenary?
2. `selection_strategy.lua = 'row'` is broken but that is also broken in current master. Its initialized wrong with `sorting_strategy = 'decending'` and i kinda expect it to do something slightly different. Or at least a while ago i fixed it to something different. E.g. I am at row index 20 and after typing there are only 15 row entries left, i expect it to be on the last possible index but now it resets. It might be the scroller?!

**Comment by tjdevries** [comment]
For now, just ignore multi selection. I just fixed some bugs I noticed along the way. I will work on that next. This is primarily focused on sending to quickfix list and making sure that results show correctly

**Comment by kaddkaka** [comment]
@Conni2461 referred me to this PR for some scroller issues. So I hope it's ok that I mention this one here too:

Pressing `<down>` when the search result is empty generates an error that steals the focus for about 1 second (new inserted characters will not be seen for that second but show up later). The error is:

`E5108: Error executing lua ...se/opt/telescope.nvim/lua/telescope/pickers/scroller.lua:66: Must never exceed max results: { result = 35, args = { 35 0 35 } }`

**Pull request merged**
