### PR TITLE
refactor(mappings): use vim.keymap and remove `__TelescopeKeymapStore`

### PR DESCRIPTION
**Pull request by Conni2461**

### CODE REVIEW

**Comment by Conni2461** [comment]
i ran it for a couple of hours with no regressions, i think this should be good to go! after that i would actually even backport it to 0.1.x if nothing breaks and then 0.1.2

**Comment by clason** [comment]
found a regression: `['<c-h>'] = 'which_key',` no longer works

**Comment by Conni2461** [comment]
oh yeah because it used the global to find mappings, forgot about that

**Comment by clason** [comment]
Guess I'll just have to start learning the mappings ;)

**Comment by Conni2461** [comment]
i think we should use `nvim_buf_get_keymap` and we just set the name as a mappings desc

**Pull request merged**
