### PR TITLE
docs: update builtin.file_browser options

### PR DESCRIPTION
**Pull request by davidmh**
Removes the unsued `search_dirs` option, and adds `cwd` and `depth`.

### CODE REVIEW

**Comment by Conni2461** [comment]
The documentation is autogenerated. You would need to update the documentation here:
https://github.com/nvim-telescope/telescope.nvim/blob/5b6b23a3a275626187ad0fbd25604b126cc6de73/lua/telescope/builtin/init.lua#L72

And make sure your fork has all action permissions. The docgen action runs in your repo, so it can push te updated documentation

**Comment by davidmh** [comment]
Thanks, @Conni2461. I'll do that later today.

**Comment by davidmh** [comment]
Alright @Conni2461, updated the code and made sure the fork has all the action permissions.

Looks like a maintaner needs to approve the workflows though.

**Comment by Conni2461** [comment]
Someone approved it actions and i don't see any generated commit. The whole approving thing makes this whole issue pop up more often but I think " Allow all actions " and " Read and write permissions " needs to be set in your fork. The actions should also run in your repo otherwise github actions can't push onto that branch.

You can then trigger ci again with a `commit --amend`, force push.

Otherwise LGTM thanks :)

**Comment by davidmh** [comment]
Weird, both settings seem to be correct in my fork 

image

I'll force push either way

**Comment by davidmh** [comment]
Huh, nothing

**Comment by Conni2461** [comment]
Okay :| i blame github and just ran `docgen` locally :rofl: 

Thanks :)

**Pull request merged**
