### PR TITLE
Fix file_ingore_patterns for tags and lsp

### LINKED ISSUE #299: file_ignore_patterns breaks tags and lsp
### Description
 
 Setting `file_ignore_patterns` value to tags, breaks tags picker

 **Expected Behavior**
 
 Adding tags to file_ignore_patterns should be ignored and not cause tag picker to break

 **Actual Behavior**
 

 After setting file_ignore to `{'tags'}` results in the the following error

 ```vim
 [telescope] [WARN  22:51:44] /tmp/plugged/telescope.nvim/lua/telescope/pickers.lua:527: Failed with msg:  /tmp/plugged/telescope.nvim/lua/telescope/pickers.lua:442: bad argument #1 to 'find' (string expected, got nil)
 
 ```

 ### Details

 
 <details><summary>Reproduce</summary>

 1. nvim -nu test.vim
 2. :Telescope tags
 3. error
 </details>

 
 <details><summary>Environment</summary>

 
 - nvim version: master
 - Operating system: arch
 - Telescope commit: 7514137e2acade815fec910ceedd9a08b9d5200f

 </details>

 
 <details><summary>Configuration</summary>
 <p>
 

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close | Telescope tags
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {'tags'},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

### PR DESCRIPTION
**Pull request by Conni2461**
Fix #299 

@weilbith @tami5

### CODE REVIEW

**Comment by tami5** [comment]
Testing ....

**Comment by tami5** [comment]
Works good for me. No more issue with having tags in file_ignore. @weilbith can you test it

**Comment by weilbith** [comment]
I'm sorry. I must admit that I have issues to switch with my plugin manager `dein` to a fork. So it did so and it does not work for me, but I'm not sure if that is because of the setup or it is just not fixed for me. 
So I would suggest that you merge it, because it apparently solves some issue. And if my problem then still remains I can open a new issue for that or re-open the existing one.

PS: I'll improve how to test forks in future. Actually planning to do a bigger refactoring towards packages anyways. Kinda waiting for `packer.nvim` to get more stable and feature complete...

**Comment by tami5** [comment]
@weilbith dein is so good but its a bit painful to use. I suggest just adding the patch to the file edited here and see. Its few lines, and if it doesn't work then further testing is needed.

Can you share your ignore patterns

**Comment by weilbith** [comment]
> @weilbith dein is so good but its a bit painful to use. I suggest just adding the patch to the file edited here and see.

Unfortunately true. :expressionless: 

> Its few lines, and if it doesn't work then further testing is needed.

Okay I did so, and it does not work. So now cloned the repo myself and used it as a local plugin. But this branch is way behind and has no `lsp` builtin. So I can't test it...

**Comment by Conni2461** [comment]
> But this branch is way behind and has no lsp builtin. So I can't test it...

Not my master branch. That one is behind like 100 years :laughing:. `fix_file_ignore_patterns` in my fork is 1 commit ahead of master. So up to date.
You can also do `git fetch origin pull/309/head:pr-309` and than `git checkout pr-309` when using this repo

**Comment by weilbith** [comment]
Ah sorry I could just use master on the local plugin and apply the changes again. :facepalm:

**Comment by weilbith** [comment]
And I was on the wrong branch. Mixed that with the issue that was in first place regarding tags. :expressionless:

**Comment by tami5** [comment]
Its okay @weilbith it use to happen to me. I think the new githubcli integration lets you checkout git pulls easily. Also, I suggest keeping using telescope as a local plugin until you switch or find a workaround.

**Comment by weilbith** [comment]
Soooo finally: yes it works.

This is what I did (besides cloning it and use it as a local plugin):
`:lua require('telescope').setup{defaults = { file_ignore_patterns = { '%.fls', '%.fdb_latexmk' }}}`
`:lua require('telescope.builtin.lsp').references()`

**Pull request merged**
