### PR TITLE
Cycle previewers with git commit and bcommit already using it

### LINKED ISSUE #307: feat: Builtin Bcommit switch preview content
Hey guys,
just such amazing work going on here every day.
I'm just about to remove some old plugins that have been obsolete by Telescope. One of them is related to the git commit history of the current buffer. I would love to ask if it would be possible to alternate the preview with a key mapping between:

- diff to current state
- diff to it parent commit 
- plain file as it was/is for the selected commit

That would be incredibly useful. Thanks for any feedback! 🤗

### LINKED ISSUE #627: Feature: Expand shortened result paths in the preview title
When using a layout with a vertical preview window the results window is quite narrow.
Because of this paths often get shortened to just the first letter in the results window:
```
/p/n/d/nvim-treesitter.txt:38:11:  require'nvim-treesitter.conf
```

Right now the Preview title just says "Preview" it would be really useful if the preview could show the expanded path to the file it's currently previewing.
```
Preview: plugged/nvim-treesitter/doc/nvim-treesitter.txt:38:11
```
You could probably lose the word 'Preview' as well.
I'd be happy to code this just want to see if it's something people would want inside telescope or just a recipe?

### PR DESCRIPTION
**Pull request by Conni2461**
Closes #307
Closes #627

Look at it here: https://streamable.com/sxi8fz

Continuation of #314

Edit: would be cool if we could somehow show the context of the previewer. Idk how we would do this.

### CODE REVIEW

**Comment by elianiva** [comment]
I'm a bit confused, what do you mean by `the context of the previewer` ?

**Comment by Conni2461** [comment]
Like in which previewer i am currently in like in which of the 3 are currently displayed:
- previewers.git_commit_diff_to_parent.new(opts),
- previewers.git_commit_diff_to_head.new(opts),
- previewers.git_commit_diff_as_was.new(opts),

**Comment by elianiva** [comment]
ah, ok I see. I think "context" makes sense but calling it a "name" is easier for me to understand :laughing:

**Comment by Conni2461** [comment]
We could put it where we currently have `Preview` but i don't think we can update this on the fly

**Comment by Conni2461** [comment]
Half working version: https://gist.github.com/Conni2461/d02a0216e0436cd436ca5991e2c239bb :| Way to much duplication shouldn't happen in telescope and i don't know how to proceed because of the upcoming ui module.

**Comment by Conni2461** [comment]
Okay i have the changing title. Here is a new video: https://streamable.com/n3b8aq

It requires a new PR for plenary. I will update this post after i submitted that PR.

**Comment by Conni2461** [comment]
Rebased and added something new. `diff to parent` will now also add the full commit message on top. `git diff as was` does this also but only for `git_commits` not `git_bcommits`. So i am not sure if i like this.

Thoughts @elianiva @weilbith ?

Besides that it should be done. :)

**Comment by elianiva** [comment]
GJ, works like a charm! Is it possible to switch to a custom previewer instead of predefined one? e.g file previewer to media previewer from media_files extension

**Comment by Conni2461** [comment]
Do you want it as second previewer so you can cycle or do you just want to replace the previewer? Because yes you should just be able to do that. Like with everything :laughing: Something like this:
```lua
local my_find_files = function(opts)
  opts = opts or {} -- just in case you wanna do opts. Then you have to merge tables or so
  require'telescope.builtin'.find_files {
    -- function to new previewer. Just for example bat one
    previewer = require'telescope.previewers'.cat.new(opts),
    -- or if you want to cycle
    alt_previewers = {
      -- Array of functions
      require'telescope.previewers'.cat.new(opts),
    }
  }
```
I tested this. Its really weird to jump between buffer and term previewers. But i love how its possible :rofl: 

Also if a previewer has no specific window title it will just print "Preview". So this feature works with older versions (and term previewers haven't added titles for them) but pwntester or windwp can just add them later if they want

**Comment by elianiva** [comment]
Perfect, exactly what I wanted. Thank you!

**Comment by tami5** [comment]
what about auto-deduction? for example images. So that file browser and others can switch to image preview

**Comment by weilbith** [comment]
Pretty sick. Great work! :ok_hand:

**Comment by Conni2461** [comment]
I know i kinda like it :D what about message at top of `diff to parent` should we keep it?

**Comment by weilbith** [comment]
> what about message at top of diff to parent should we keep it?

I think it is quite useful. But if it could be independent of the diff itself would be great. But I assume this is waaaay to heavy.
Because what I would like is to focus the diff on the line that the user has currently active. So you immediately see the diff related to your current location. What do you think?

**Comment by weilbith** [comment]
And while I'm already brainstorming and telling wishes: it would be great to have another action which will not checkout this commit, but put the file into a diff view. Sometimes the scrollable preview is nice, but you need a proper split view and also pull old changes into your buffer.
But that would be another PR. :grimacing:

**Comment by Conni2461** [comment]
Don't say more. You're wishes will be granted. Today or tomorrow dont know but this week 99%. Who need different PRs. 1000+ changes PR incoming. :laughing: 

- Showing current line is possible. With `vim.fn.search`.
- We can make another previewer just for message. Everything is possible. `Telescope` api is just insanely nice :laughing: I just need to define it and put it in alt_previewers table.
- Diff view should also be possible. :D

I like having so clear suggestions.

**Comment by Conni2461** [comment]
Do we wanna highlight the message? I guess so we can highlight hash, author and date

**Comment by Conni2461** [comment]
Example of the new view and highlighting i just did. Open for suggestions. We can easily also highlight just email, just name. First column anything in that header basically

**Comment by weilbith** [comment]
> Don't say more. You're wishes will be granted.

:hugging:

---

Could we have proper buffer highlighting for the "as was " file and some diff highlights for the, well yeah, diff view? In your screenshot it looks so pale. But I like the header highlights. :upside_down_face:

**Comment by Conni2461** [comment]
That screenshot shows only git message in a new preview. I just picked one where i actually described the commit :rofl:
All views should have highlighting but i am only testing lua right now so it might be broken. I am testing c later.

I am close to vimdiff on split, vsplit and tabedit mappings. Enter will still be checkout. In my opinion. Also this will only be implemented for `bcommits` so i think you can test and break it tomorrow (if you have the time) :rofl: .

**Comment by Conni2461** [comment]
I think i could have made the clip better but i am too lazy to record again. How did you do that like 100 times @elianiva :laughing: 

Here is showcase of all new features: https://streamable.com/5xu5r7

Commit follows in a sec

**Comment by weilbith** [comment]
Amazing work! This is pretty dope! Looking forward to use this is practice. :party_face: :rocket:
Thank you very much for all the time and hard work you have invested. :pray:

**Comment by tjdevries** [comment]
I don't like the names `all_previewers` and `alt_previewers`. They are too close together and too many similar letters for lua :)

We should change them before merging.

**Comment by Conni2461** [comment]
New idea. Have `previewer` field accept either one previewer or a table of previewers. And than store all of them in a `all_previewers` table inside `picker`. Have a reference for the current previewer(we still need this because actions still need access to that one because of scrolling and probably other cool things) yeah and that it.
But i thought everyone already knew that i am terrible with names. So i am also open for suggestions :rofl:

**Comment by elianiva** [comment]
I think Conni's new idea is better, we would no longer need 2 separate fields.

**Comment by Conni2461** [comment]
Addresses naming issues :)
Note this still requires:  nvim-lua/plenary.nvim#82

**Comment by Conni2461** [comment]
Okay i am like 95% done with this here, if anyone wanna try it. I still need to implement titles for old previewers and i am going to run this branch for 1,2 days after that i kinda wanna merge and move on :laughing:

**Comment by Conni2461** [comment]
Everything in telescope land is done, but dynamic title breaks everything if `title len` > `window width` because there is no truncating in plenary. So i am thinking about moving all our truncate stuff in telescope to plenary. Will talk about it with tj

And i wanted to move on :sob:

**Comment by ecosse3** [comment]
Any news? I can not wait for that 😄

**Comment by Conni2461** [comment]
:) Something is missing in plenary to make it work. Otherwise its done here. Just a rebase. I will check in on the plenary work tomorrow maybe i can help out :)

**Comment by Conni2461** [comment]
@VVKot I rebased this pr, so you can technically use it. Only `dynamic_window_titles` (or whatever i named it) might break your telescope till that plenary pr is merged. I need to go thought the whole diff again tho. I am not sure if i made a mistake while rebasing

**Comment by Conni2461** [comment]
I'll try to finish + merge it this evening (mostly just docs missing).

**Comment by VVKot** [comment]
@Conni2461 sorry, I haven't circled back here - but I did check out your branch and this looks great!

**Comment by Conni2461** [comment]
Lets give this a try. Might not be perfect but its only implemented for commits and bcommits, so we can iterate on it in the next few weeks. Maybe more people can come up with really cool things when using the api in extensions.

Its not mapped on default so you need to setup something like this:
```lua
require('telescope').setup {
  defaults = {
    mappings = {
      i = {
        ["<C-s>"] = actions.cycle_previewers_next,
        ["<C-a>"] = actions.cycle_previewers_prev,
      },
    },
  }
}
```

**Pull request merged**
